package mx.prisma.generadorPruebas.model;

// Generated Oct 26, 2015 11:38:15 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoValor generated by hbm2java
 */
@Entity
@Table(name = "TipoValor", catalog = "PRISMA")
public class TipoValor implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set valors = new HashSet(0);

	public TipoValor() {
	}

	public TipoValor(String nombre, Set valors) {
		this.nombre = nombre;
		this.valors = valors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoValor")
	public Set getValors() {
		return this.valors;
	}

	public void setValors(Set valors) {
		this.valors = valors;
	}

}
