package mx.prisma.generadorPruebas.model;

// Generated Oct 26, 2015 11:38:15 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Valor generated by hbm2java
 */
@Entity
@Table(name = "Valor", catalog = "PRISMA")
public class Valor implements java.io.Serializable {

	private Integer id;
	private TipoValor tipoValor;
	private String valor;
	private int referenciaParametroid;
	private int mensajeParametroid;

	public Valor() {
	}

	public Valor(TipoValor tipoValor, String valor, int referenciaParametroid,
			int mensajeParametroid) {
		this.tipoValor = tipoValor;
		this.valor = valor;
		this.referenciaParametroid = referenciaParametroid;
		this.mensajeParametroid = mensajeParametroid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TipoValorid", nullable = false)
	public TipoValor getTipoValor() {
		return this.tipoValor;
	}

	public void setTipoValor(TipoValor tipoValor) {
		this.tipoValor = tipoValor;
	}

	@Column(name = "valor", nullable = false)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "ReferenciaParametroid", nullable = false)
	public int getReferenciaParametroid() {
		return this.referenciaParametroid;
	}

	public void setReferenciaParametroid(int referenciaParametroid) {
		this.referenciaParametroid = referenciaParametroid;
	}

	@Column(name = "Mensaje_Parametroid", nullable = false)
	public int getMensajeParametroid() {
		return this.mensajeParametroid;
	}

	public void setMensajeParametroid(int mensajeParametroid) {
		this.mensajeParametroid = mensajeParametroid;
	}

}
