package mx.prisma.admin.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ColaboradorProyecto generated by hbm2java
 */
@Entity
@Table(name = "Colaborador_Proyecto", catalog = "PRISMA")
public class ColaboradorProyecto implements java.io.Serializable {

	private ColaboradorProyectoId id;
	private int rolidentificador;

	public ColaboradorProyecto() {
	}

	public ColaboradorProyecto(ColaboradorProyectoId id, int rolidentificador) {
		this.id = id;
		this.rolidentificador = rolidentificador;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "colaboradorCurp", column = @Column(name = "ColaboradorCURP", nullable = false, length = 18)),
			@AttributeOverride(name = "proyectoclave", column = @Column(name = "Proyectoclave", nullable = false, length = 10)) })
	public ColaboradorProyectoId getId() {
		return this.id;
	}

	public void setId(ColaboradorProyectoId id) {
		this.id = id;
	}

	@Column(name = "Rolidentificador", nullable = false)
	public int getRolidentificador() {
		return this.rolidentificador;
	}

	public void setRolidentificador(int rolidentificador) {
		this.rolidentificador = rolidentificador;
	}

}
