package mx.prisma.admin.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import mx.prisma.admin.model.Telefono;

/**
 * Colaborador generated by hbm2java
 */
@Entity
@Table(name = "Colaborador", catalog = "PRISMA")
public class Colaborador implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String curp;
	private String nombre;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String correoElectronico;
	private String contrasenia;
	private Set<ColaboradorProyecto> proyectos = new HashSet<ColaboradorProyecto>(0);
	private Set<Telefono> telefonos = new HashSet<Telefono>(0);


	public Colaborador() {
	}

	public Colaborador(String curp, String nombre, String apellidoPaterno,
			String apellidoMaterno, String correoElectronico, String contrasenia, Set<Telefono> telefonos) {
		this.curp = curp;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.correoElectronico = correoElectronico;
		this.contrasenia = contrasenia;
	}
	public Colaborador(String curp, String nombre, String apellidoPaterno,
			String apellidoMaterno, String correoElectronico, String contrasenia) {
		this.curp = curp;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.correoElectronico = correoElectronico;
		this.contrasenia = contrasenia;
	}

	@Id
	@Column(name = "CURP", unique = true, nullable = false, length = 18)
	public String getCurp() {
		return this.curp;
	}

	public void setCurp(String curp) {
		this.curp = curp;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidoPaterno", nullable = false, length = 45)
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "apellidoMaterno", nullable = false, length = 45)
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "correoElectronico", nullable = false, length = 45)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "contrasenia", nullable = false, length = 20)
	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "id.colaborador", cascade = CascadeType.ALL)
	public Set<ColaboradorProyecto> getProyectos() {
		return proyectos;
	}

	public void setProyectos(Set<ColaboradorProyecto> proyectos) {
		this.proyectos = proyectos;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.colaborador", cascade = CascadeType.ALL)
	public Set<Telefono> getTelefonos() {
		return telefonos;
	}

	public void setTelefonos(Set<Telefono> telefonos) {
		this.telefonos = telefonos;
	}



}
