package mx.prisma.admin.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0


import javax.persistence.CascadeType;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ColaboradorProyecto generated by hbm2java
 */
@Entity
@Table(name = "Colaborador_Proyecto", catalog = "PRISMA")
public class ColaboradorProyecto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ColaboradorProyectoId id;
	private Rol rol;

	public ColaboradorProyecto() {
	}

	public ColaboradorProyecto(ColaboradorProyectoId id, Rol rol) {
		this.id = id;
		this.rol = rol;
	}

	@EmbeddedId
	public ColaboradorProyectoId getId() {
		return this.id;
	}

	public void setId(ColaboradorProyectoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "Rolidentificador", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}
	

	
	

	
}
