package mx.prisma.admin.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ColaboradorProyectoId generated by hbm2java
 */
@Embeddable
public class ColaboradorProyectoId implements java.io.Serializable {

	private String colaboradorCurp;
	private String proyectoclave;

	public ColaboradorProyectoId() {
	}

	public ColaboradorProyectoId(String colaboradorCurp, String proyectoclave) {
		this.colaboradorCurp = colaboradorCurp;
		this.proyectoclave = proyectoclave;
	}

	@Column(name = "ColaboradorCURP", nullable = false, length = 18)
	public String getColaboradorCurp() {
		return this.colaboradorCurp;
	}

	public void setColaboradorCurp(String colaboradorCurp) {
		this.colaboradorCurp = colaboradorCurp;
	}

	@Column(name = "Proyectoclave", nullable = false, length = 10)
	public String getProyectoclave() {
		return this.proyectoclave;
	}

	public void setProyectoclave(String proyectoclave) {
		this.proyectoclave = proyectoclave;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColaboradorProyectoId))
			return false;
		ColaboradorProyectoId castOther = (ColaboradorProyectoId) other;

		return ((this.getColaboradorCurp() == castOther.getColaboradorCurp()) || (this
				.getColaboradorCurp() != null
				&& castOther.getColaboradorCurp() != null && this
				.getColaboradorCurp().equals(castOther.getColaboradorCurp())))
				&& ((this.getProyectoclave() == castOther.getProyectoclave()) || (this
						.getProyectoclave() != null
						&& castOther.getProyectoclave() != null && this
						.getProyectoclave()
						.equals(castOther.getProyectoclave())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getColaboradorCurp() == null ? 0 : this.getColaboradorCurp()
						.hashCode());
		result = 37
				* result
				+ (getProyectoclave() == null ? 0 : this.getProyectoclave()
						.hashCode());
		return result;
	}

}
