package mx.prisma.admin.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import mx.prisma.editor.model.Elemento;

/**
 * EstadoProyecto generated by hbm2java
 */
@Entity
@Table(name = "EstadoProyecto", catalog = "PRISMA")
public class EstadoProyecto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer identificador;
	private String nombre;
	private Set<Elemento> elementos = new HashSet<Elemento>(0);

	public EstadoProyecto() {
	}

	public EstadoProyecto(String nombre) {
		this.nombre = nombre;
	}
	public EstadoProyecto(String nombre, Set<Elemento> elementos) {
		this.nombre = nombre;
		this.elementos = elementos;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "identificador", unique = true, nullable = false)
	public Integer getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Integer identificador) {
		this.identificador = identificador;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proyecto")
	public Set<Elemento> getElementos() {
		return this.elementos;
	}
 
	public void setElementos(Set<Elemento> elementos) {
		this.elementos = elementos;
	}	

}
