package mx.prisma.admin.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "Rol", catalog = "PRISMA")
public class Rol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer identificador;
	private String nombre;
	private Set<ColaboradorProyecto> colaboradores = new HashSet<ColaboradorProyecto>(0);

	public Rol() {
	}

	public Rol(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "identificador", unique = true, nullable = false)
	public Integer getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Integer identificador) {
		this.identificador = identificador;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<ColaboradorProyecto> getColaboradores() {
		return colaboradores;
	}

	public void setColaboradores(Set<ColaboradorProyecto> colaboradores) {
		this.colaboradores = colaboradores;
	}

}
