package mx.prisma.admin.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name = "Telefono", catalog = "PRISMA")
public class Telefono implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TelefonoId id;
	
	public Telefono() {
	}
	public Telefono(TelefonoId id) {
		this.id = id;
	}
	@EmbeddedId
	public TelefonoId getId() {
		return id;
	}
	public void setId(TelefonoId id) {
		this.id = id;
	}

}
