package mx.prisma.admin.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TelefonoId generated by hbm2java
 */
@Embeddable
public class TelefonoId implements java.io.Serializable {

	private String colaboradorCurp;
	private String lada;
	private String numero;
	private String extesion;

	public TelefonoId() {
	}

	public TelefonoId(String colaboradorCurp, String lada, String numero,
			String extesion) {
		this.colaboradorCurp = colaboradorCurp;
		this.lada = lada;
		this.numero = numero;
		this.extesion = extesion;
	}

	@Column(name = "ColaboradorCURP", nullable = false, length = 18)
	public String getColaboradorCurp() {
		return this.colaboradorCurp;
	}

	public void setColaboradorCurp(String colaboradorCurp) {
		this.colaboradorCurp = colaboradorCurp;
	}

	@Column(name = "lada", nullable = false, length = 5)
	public String getLada() {
		return this.lada;
	}

	public void setLada(String lada) {
		this.lada = lada;
	}

	@Column(name = "numero", nullable = false, length = 10)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "extesion", nullable = false, length = 10)
	public String getExtesion() {
		return this.extesion;
	}

	public void setExtesion(String extesion) {
		this.extesion = extesion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TelefonoId))
			return false;
		TelefonoId castOther = (TelefonoId) other;

		return ((this.getColaboradorCurp() == castOther.getColaboradorCurp()) || (this
				.getColaboradorCurp() != null
				&& castOther.getColaboradorCurp() != null && this
				.getColaboradorCurp().equals(castOther.getColaboradorCurp())))
				&& ((this.getLada() == castOther.getLada()) || (this.getLada() != null
						&& castOther.getLada() != null && this.getLada()
						.equals(castOther.getLada())))
				&& ((this.getNumero() == castOther.getNumero()) || (this
						.getNumero() != null && castOther.getNumero() != null && this
						.getNumero().equals(castOther.getNumero())))
				&& ((this.getExtesion() == castOther.getExtesion()) || (this
						.getExtesion() != null
						&& castOther.getExtesion() != null && this
						.getExtesion().equals(castOther.getExtesion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getColaboradorCurp() == null ? 0 : this.getColaboradorCurp()
						.hashCode());
		result = 37 * result
				+ (getLada() == null ? 0 : this.getLada().hashCode());
		result = 37 * result
				+ (getNumero() == null ? 0 : this.getNumero().hashCode());
		result = 37 * result
				+ (getExtesion() == null ? 0 : this.getExtesion().hashCode());
		return result;
	}

}
