package mx.prisma.bs;

public class AnalisisEnum {
	public enum CU_CasosUso {
		MODIFICARCASOUSO5_2,
		ELIMINARCASOUSO5_3,
		MODIFICARTRAYECTORIA5_1_1_2,
		ELIMINARTRAYECTORIA5_1_1_3
	}
	
	public enum CU_Mensajes {
		MODIFICARMENSAJE9_2,
		ELIMINARMENSAJE9_3
	}
	public enum CU_ReglasNegocio {
		MODIFICARREGLANEGOCIO8_2, ELIMINARREGLANEGOCIO8_3
	}
	public enum CU_Pantallas {
		MODIFICARPANTALLA6_2, ELIMINARPANTALLA6_3  
	}
	public enum CU_Actores {
		MODIFICARACTOR7_2, ELIMINARACTOR7_3  
	}
	public enum CU_Glosario {
		MODIFICARTERMINO10_2, ELIMINARTERMINO10_3  
	}
	public enum CU_Entidades {
		MODIFICARENTIDAD11_2, ELIMINARENTIDAD11_3  
	}
}
