package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccionId generated by hbm2java
 */
@Embeddable
public class AccionId implements java.io.Serializable {

	private String pantallaElementoclave;
	private int pantallaElementonumero;
	private String pantallaElementonombre;
	private String nombre;

	public AccionId() {
	}

	public AccionId(String pantallaElementoclave, int pantallaElementonumero,
			String pantallaElementonombre, String nombre) {
		this.pantallaElementoclave = pantallaElementoclave;
		this.pantallaElementonumero = pantallaElementonumero;
		this.pantallaElementonombre = pantallaElementonombre;
		this.nombre = nombre;
	}

	@Column(name = "PantallaElementoclave", nullable = false, length = 10)
	public String getPantallaElementoclave() {
		return this.pantallaElementoclave;
	}

	public void setPantallaElementoclave(String pantallaElementoclave) {
		this.pantallaElementoclave = pantallaElementoclave;
	}

	@Column(name = "PantallaElementonumero", nullable = false)
	public int getPantallaElementonumero() {
		return this.pantallaElementonumero;
	}

	public void setPantallaElementonumero(int pantallaElementonumero) {
		this.pantallaElementonumero = pantallaElementonumero;
	}

	@Column(name = "PantallaElementonombre", nullable = false, length = 45)
	public String getPantallaElementonombre() {
		return this.pantallaElementonombre;
	}

	public void setPantallaElementonombre(String pantallaElementonombre) {
		this.pantallaElementonombre = pantallaElementonombre;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccionId))
			return false;
		AccionId castOther = (AccionId) other;

		return ((this.getPantallaElementoclave() == castOther
				.getPantallaElementoclave()) || (this
				.getPantallaElementoclave() != null
				&& castOther.getPantallaElementoclave() != null && this
				.getPantallaElementoclave().equals(
						castOther.getPantallaElementoclave())))
				&& (this.getPantallaElementonumero() == castOther
						.getPantallaElementonumero())
				&& ((this.getPantallaElementonombre() == castOther
						.getPantallaElementonombre()) || (this
						.getPantallaElementonombre() != null
						&& castOther.getPantallaElementonombre() != null && this
						.getPantallaElementonombre().equals(
								castOther.getPantallaElementonombre())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPantallaElementoclave() == null ? 0 : this
						.getPantallaElementoclave().hashCode());
		result = 37 * result + this.getPantallaElementonumero();
		result = 37
				* result
				+ (getPantallaElementonombre() == null ? 0 : this
						.getPantallaElementonombre().hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		return result;
	}

}
