package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.PrimaryKeyJoinColumns;
import javax.persistence.Table;

import mx.prisma.admin.model.Proyecto;

/**
 * Actor generated by hbm2java
 */
@Entity
@Table(name = "Actor", catalog = "PRISMA")
@PrimaryKeyJoinColumns({
		@PrimaryKeyJoinColumn(name = "Elementoclave", referencedColumnName = "clave"),
		@PrimaryKeyJoinColumn(name = "Elementonumero", referencedColumnName = "numero"),
		@PrimaryKeyJoinColumn(name = "Elementonombre", referencedColumnName = "nombre") })
public class Actor extends Elemento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String descripcion;
	private Cardinalidad cardinalidad;
	private String otraCardinalidad;

	public Actor() {
	}
	public Actor(ElementoId id, EstadoElemento estadoElemento, Proyecto proyecto, String descripcion, Cardinalidad cardinalidad, String otraCardinalidad) {
		super(id, estadoElemento, proyecto);
		this.descripcion = descripcion;
		this.cardinalidad = cardinalidad;
		this.otraCardinalidad = otraCardinalidad;
	}
	public Actor(ElementoId id, String descripcion, Cardinalidad cardinalidad) {
		this.descripcion = descripcion;
		this.cardinalidad = cardinalidad;
	}

	@Column(name = "descripcion", nullable = false, length = 999)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cardinalidadidentificador", nullable = false)
	public Cardinalidad getCardinalidad() {
		return this.cardinalidad;
	}
 
	public void setCardinalidad(Cardinalidad cardinalidad) {
		this.cardinalidad = cardinalidad;
	}
 

	@Column(name = "otraCardinalidad", nullable = false, length = 10)
	public String getOtraCardinalidad() {
		return this.otraCardinalidad;
	}

	public void setOtraCardinalidad(String otraCardinalidad) {
		this.otraCardinalidad = otraCardinalidad;
	}

}
