package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActualizacionId generated by hbm2java
 */
@Embeddable
public class ActualizacionId implements java.io.Serializable {

	private String elementoclave;
	private int elementonumero;
	private String elementonombre;
	private String colaboradorProyectoColaboradorCurp;
	private String colaboradorProyectoProyectoclave;

	public ActualizacionId() {
	}

	public ActualizacionId(String elementoclave, int elementonumero,
			String elementonombre, String colaboradorProyectoColaboradorCurp,
			String colaboradorProyectoProyectoclave) {
		this.elementoclave = elementoclave;
		this.elementonumero = elementonumero;
		this.elementonombre = elementonombre;
		this.colaboradorProyectoColaboradorCurp = colaboradorProyectoColaboradorCurp;
		this.colaboradorProyectoProyectoclave = colaboradorProyectoProyectoclave;
	}

	@Column(name = "Elementoclave", nullable = false, length = 10)
	public String getElementoclave() {
		return this.elementoclave;
	}

	public void setElementoclave(String elementoclave) {
		this.elementoclave = elementoclave;
	}

	@Column(name = "Elementonumero", nullable = false)
	public int getElementonumero() {
		return this.elementonumero;
	}

	public void setElementonumero(int elementonumero) {
		this.elementonumero = elementonumero;
	}

	@Column(name = "Elementonombre", nullable = false, length = 45)
	public String getElementonombre() {
		return this.elementonombre;
	}

	public void setElementonombre(String elementonombre) {
		this.elementonombre = elementonombre;
	}

	@Column(name = "Colaborador_ProyectoColaboradorCURP", nullable = false, length = 18)
	public String getColaboradorProyectoColaboradorCurp() {
		return this.colaboradorProyectoColaboradorCurp;
	}

	public void setColaboradorProyectoColaboradorCurp(
			String colaboradorProyectoColaboradorCurp) {
		this.colaboradorProyectoColaboradorCurp = colaboradorProyectoColaboradorCurp;
	}

	@Column(name = "Colaborador_ProyectoProyectoclave", nullable = false, length = 10)
	public String getColaboradorProyectoProyectoclave() {
		return this.colaboradorProyectoProyectoclave;
	}

	public void setColaboradorProyectoProyectoclave(
			String colaboradorProyectoProyectoclave) {
		this.colaboradorProyectoProyectoclave = colaboradorProyectoProyectoclave;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActualizacionId))
			return false;
		ActualizacionId castOther = (ActualizacionId) other;

		return ((this.getElementoclave() == castOther.getElementoclave()) || (this
				.getElementoclave() != null
				&& castOther.getElementoclave() != null && this
				.getElementoclave().equals(castOther.getElementoclave())))
				&& (this.getElementonumero() == castOther.getElementonumero())
				&& ((this.getElementonombre() == castOther.getElementonombre()) || (this
						.getElementonombre() != null
						&& castOther.getElementonombre() != null && this
						.getElementonombre().equals(
								castOther.getElementonombre())))
				&& ((this.getColaboradorProyectoColaboradorCurp() == castOther
						.getColaboradorProyectoColaboradorCurp()) || (this
						.getColaboradorProyectoColaboradorCurp() != null
						&& castOther.getColaboradorProyectoColaboradorCurp() != null && this
						.getColaboradorProyectoColaboradorCurp()
						.equals(castOther
								.getColaboradorProyectoColaboradorCurp())))
				&& ((this.getColaboradorProyectoProyectoclave() == castOther
						.getColaboradorProyectoProyectoclave()) || (this
						.getColaboradorProyectoProyectoclave() != null
						&& castOther.getColaboradorProyectoProyectoclave() != null && this
						.getColaboradorProyectoProyectoclave()
						.equals(castOther.getColaboradorProyectoProyectoclave())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getElementoclave() == null ? 0 : this.getElementoclave()
						.hashCode());
		result = 37 * result + this.getElementonumero();
		result = 37
				* result
				+ (getElementonombre() == null ? 0 : this.getElementonombre()
						.hashCode());
		result = 37
				* result
				+ (getColaboradorProyectoColaboradorCurp() == null ? 0 : this
						.getColaboradorProyectoColaboradorCurp().hashCode());
		result = 37
				* result
				+ (getColaboradorProyectoProyectoclave() == null ? 0 : this
						.getColaboradorProyectoProyectoclave().hashCode());
		return result;
	}

}
