package mx.prisma.editor.model;

// Generated 07-jun-2015 17:10:34 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actualizacion generated by hbm2java
 */
@Entity
@Table(name = "Actualizacion", catalog = "PRISMA")
public class Actualizacion implements java.io.Serializable {

	private Integer id;
	private Date fecha;
	private String comentario;
	private int estadoElementoidPre;
	private int estadoElementoidPost;
	private int elementoid;
	private int colaboradorProyectoid;

	public Actualizacion() {
	}

	public Actualizacion(Date fecha, String comentario,
			int estadoElementoidPre, int estadoElementoidPost, int elementoid,
			int colaboradorProyectoid) {
		this.fecha = fecha;
		this.comentario = comentario;
		this.estadoElementoidPre = estadoElementoidPre;
		this.estadoElementoidPost = estadoElementoidPost;
		this.elementoid = elementoid;
		this.colaboradorProyectoid = colaboradorProyectoid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "comentario", nullable = false, length = 999)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "EstadoElementoidPre", nullable = false)
	public int getEstadoElementoidPre() {
		return this.estadoElementoidPre;
	}

	public void setEstadoElementoidPre(int estadoElementoidPre) {
		this.estadoElementoidPre = estadoElementoidPre;
	}

	@Column(name = "EstadoElementoidPost", nullable = false)
	public int getEstadoElementoidPost() {
		return this.estadoElementoidPost;
	}

	public void setEstadoElementoidPost(int estadoElementoidPost) {
		this.estadoElementoidPost = estadoElementoidPost;
	}

	@Column(name = "Elementoid", nullable = false)
	public int getElementoid() {
		return this.elementoid;
	}

	public void setElementoid(int elementoid) {
		this.elementoid = elementoid;
	}

	@Column(name = "Colaborador_Proyectoid", nullable = false)
	public int getColaboradorProyectoid() {
		return this.colaboradorProyectoid;
	}

	public void setColaboradorProyectoid(int colaboradorProyectoid) {
		this.colaboradorProyectoid = colaboradorProyectoid;
	}

}
