package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actualizacion generated by hbm2java
 */
@Entity
@Table(name = "Actualizacion", catalog = "PRISMA")
public class Actualizacion implements java.io.Serializable {

	private ActualizacionId id;
	private Date fecha;
	private String comentario;
	private int estadoElementoidentificadorPre;
	private int estadoElementoidentificadorPost;

	public Actualizacion() {
	}

	public Actualizacion(ActualizacionId id, Date fecha, String comentario,
			int estadoElementoidentificadorPre,
			int estadoElementoidentificadorPost) {
		this.id = id;
		this.fecha = fecha;
		this.comentario = comentario;
		this.estadoElementoidentificadorPre = estadoElementoidentificadorPre;
		this.estadoElementoidentificadorPost = estadoElementoidentificadorPost;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "elementoclave", column = @Column(name = "Elementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "elementonumero", column = @Column(name = "Elementonumero", nullable = false)),
			@AttributeOverride(name = "elementonombre", column = @Column(name = "Elementonombre", nullable = false, length = 45)),
			@AttributeOverride(name = "colaboradorProyectoColaboradorCurp", column = @Column(name = "Colaborador_ProyectoColaboradorCURP", nullable = false, length = 18)),
			@AttributeOverride(name = "colaboradorProyectoProyectoclave", column = @Column(name = "Colaborador_ProyectoProyectoclave", nullable = false, length = 10)) })
	public ActualizacionId getId() {
		return this.id;
	}

	public void setId(ActualizacionId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "comentario", nullable = false, length = 999)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "EstadoElementoidentificadorPre", nullable = false)
	public int getEstadoElementoidentificadorPre() {
		return this.estadoElementoidentificadorPre;
	}

	public void setEstadoElementoidentificadorPre(
			int estadoElementoidentificadorPre) {
		this.estadoElementoidentificadorPre = estadoElementoidentificadorPre;
	}

	@Column(name = "EstadoElementoidentificadorPost", nullable = false)
	public int getEstadoElementoidentificadorPost() {
		return this.estadoElementoidentificadorPost;
	}

	public void setEstadoElementoidentificadorPost(
			int estadoElementoidentificadorPost) {
		this.estadoElementoidentificadorPost = estadoElementoidentificadorPost;
	}

}
