package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Atributo generated by hbm2java
 */
@Entity
@Table(name = "Atributo", catalog = "PRISMA")
public class Atributo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AtributoId idAtributo;
	private String descripcion;
	private boolean obligatorio;
	private int longitud;

	
	public Atributo() {
	}

	public Atributo(AtributoId idAtributo, String descripcion, boolean obligatorio,
			int longitud) {
		this.idAtributo = idAtributo;
		this.descripcion = descripcion;
		this.obligatorio = obligatorio;
		this.longitud = longitud;
	}

	@Column(name = "descripcion", nullable = false, length = 999)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "obligatorio", nullable = false)
	public boolean isObligatorio() {
		return this.obligatorio;
	}

	public void setObligatorio(boolean obligatorio) {
		this.obligatorio = obligatorio;
	}

	@Column(name = "longitud", nullable = false)
	public int getLongitud() {
		return this.longitud;
	}

	public void setLongitud(int longitud) {
		this.longitud = longitud;
	}
	
	@EmbeddedId
	public AtributoId getIdAtributo() {
		return idAtributo;
	}

	public void setIdAtributo(AtributoId idAtributo) {
		this.idAtributo = idAtributo;
	}
	
}