package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AtributoId generated by hbm2java
 */
@Embeddable
public class AtributoId implements java.io.Serializable {

	private String elementoclave;
	private int elementonumero;
	private String elementonombre;
	private String entidadElementoclave;
	private int entidadElementonumero;
	private String entidadElementonombre;

	public AtributoId() {
	}

	public AtributoId(String elementoclave, int elementonumero,
			String elementonombre, String entidadElementoclave,
			int entidadElementonumero, String entidadElementonombre) {
		this.elementoclave = elementoclave;
		this.elementonumero = elementonumero;
		this.elementonombre = elementonombre;
		this.entidadElementoclave = entidadElementoclave;
		this.entidadElementonumero = entidadElementonumero;
		this.entidadElementonombre = entidadElementonombre;
	}

	@Column(name = "Elementoclave", nullable = false, length = 10)
	public String getElementoclave() {
		return this.elementoclave;
	}

	public void setElementoclave(String elementoclave) {
		this.elementoclave = elementoclave;
	}

	@Column(name = "Elementonumero", nullable = false)
	public int getElementonumero() {
		return this.elementonumero;
	}

	public void setElementonumero(int elementonumero) {
		this.elementonumero = elementonumero;
	}

	@Column(name = "Elementonombre", nullable = false, length = 45)
	public String getElementonombre() {
		return this.elementonombre;
	}

	public void setElementonombre(String elementonombre) {
		this.elementonombre = elementonombre;
	}

	@Column(name = "EntidadElementoclave", nullable = false, length = 10)
	public String getEntidadElementoclave() {
		return this.entidadElementoclave;
	}

	public void setEntidadElementoclave(String entidadElementoclave) {
		this.entidadElementoclave = entidadElementoclave;
	}

	@Column(name = "EntidadElementonumero", nullable = false)
	public int getEntidadElementonumero() {
		return this.entidadElementonumero;
	}

	public void setEntidadElementonumero(int entidadElementonumero) {
		this.entidadElementonumero = entidadElementonumero;
	}

	@Column(name = "EntidadElementonombre", nullable = false, length = 45)
	public String getEntidadElementonombre() {
		return this.entidadElementonombre;
	}

	public void setEntidadElementonombre(String entidadElementonombre) {
		this.entidadElementonombre = entidadElementonombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AtributoId))
			return false;
		AtributoId castOther = (AtributoId) other;

		return ((this.getElementoclave() == castOther.getElementoclave()) || (this
				.getElementoclave() != null
				&& castOther.getElementoclave() != null && this
				.getElementoclave().equals(castOther.getElementoclave())))
				&& (this.getElementonumero() == castOther.getElementonumero())
				&& ((this.getElementonombre() == castOther.getElementonombre()) || (this
						.getElementonombre() != null
						&& castOther.getElementonombre() != null && this
						.getElementonombre().equals(
								castOther.getElementonombre())))
				&& ((this.getEntidadElementoclave() == castOther
						.getEntidadElementoclave()) || (this
						.getEntidadElementoclave() != null
						&& castOther.getEntidadElementoclave() != null && this
						.getEntidadElementoclave().equals(
								castOther.getEntidadElementoclave())))
				&& (this.getEntidadElementonumero() == castOther
						.getEntidadElementonumero())
				&& ((this.getEntidadElementonombre() == castOther
						.getEntidadElementonombre()) || (this
						.getEntidadElementonombre() != null
						&& castOther.getEntidadElementonombre() != null && this
						.getEntidadElementonombre().equals(
								castOther.getEntidadElementonombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getElementoclave() == null ? 0 : this.getElementoclave()
						.hashCode());
		result = 37 * result + this.getElementonumero();
		result = 37
				* result
				+ (getElementonombre() == null ? 0 : this.getElementonombre()
						.hashCode());
		result = 37
				* result
				+ (getEntidadElementoclave() == null ? 0 : this
						.getEntidadElementoclave().hashCode());
		result = 37 * result + this.getEntidadElementonumero();
		result = 37
				* result
				+ (getEntidadElementonombre() == null ? 0 : this
						.getEntidadElementonombre().hashCode());
		return result;
	}

}
