package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;

/**
 * AtributoId generated by hbm2java
 */
@Embeddable
public class AtributoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Entidad entidad;
	private String nombre;

	public AtributoId() {
	}

	public AtributoId(Entidad entidad, String nombre) {
		this.entidad = entidad;
	}
	
	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "EntidadElementoclave", referencedColumnName = "Elementoclave"),
		@JoinColumn(name = "EntidadElementonumero", referencedColumnName = "Elementonumero"),
		@JoinColumn(name = "EntidadElementonombre", referencedColumnName = "Elementonombre")
		})	
	public Entidad getEntidad() {
		return entidad;
	}

	public void setEntidad(Entidad entidad) {
		this.entidad = entidad;
	}

}