package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cardinalidad generated by hbm2java
 */
@Entity
@Table(name = "Cardinalidad", catalog = "PRISMA")
public class Cardinalidad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer identificador;
	private String nombre;
	private Set<Actor> actores = new HashSet<Actor>(0);

	public Cardinalidad() {
	}

	public Cardinalidad(String nombre) {
		this.nombre = nombre;
	}
	
	public Cardinalidad(String nombre, Set<Actor> actores) {
		this.nombre = nombre;
		this.actores = actores;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "identificador", unique = true, nullable = false)
	public Integer getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Integer identificador) {
		this.identificador = identificador;
	}

	@Column(name = "nombre", nullable = false, length = 10)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cardinalidad")
	public Set<Actor> getActores() {
		return this.actores;
	}
 
	public void setActores(Set<Actor> actores) {
		this.actores = actores;
	}

}
