package mx.prisma.editor.model;

// Generated 07-jun-2015 17:10:34 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CasoUsoReglaNegocio generated by hbm2java
 */
@Entity
@Table(name = "CasoUso_ReglaNegocio", catalog = "PRISMA")
public class CasoUsoReglaNegocio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CasoUsoReglaNegocioId id;
	private int numeroToken;

	public CasoUsoReglaNegocio() {
	}

	public CasoUsoReglaNegocio(CasoUsoReglaNegocioId id, int numeroToken) {
		this.id = id;
		this.numeroToken = numeroToken;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "casoUsoElementoid", column = @Column(name = "CasoUsoElementoid", nullable = false)),
			@AttributeOverride(name = "reglaNegocioElementoid", column = @Column(name = "ReglaNegocioElementoid", nullable = false)) })
	public CasoUsoReglaNegocioId getId() {
		return this.id;
	}

	public void setId(CasoUsoReglaNegocioId id) {
		this.id = id;
	}

	@Column(name = "numeroToken", nullable = false)
	public int getNumeroToken() {
		return this.numeroToken;
	}

	public void setNumeroToken(int numeroToken) {
		this.numeroToken = numeroToken;
	}

}
