package mx.prisma.editor.model;

// Generated 07-jun-2015 17:10:34 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CasoUsoPantallaId generated by hbm2java
 */
@Embeddable
public class CasoUsoPantallaId implements java.io.Serializable {

	private int pantallaElementoid;
	private int casoUsoElementoid;

	public CasoUsoPantallaId() {
	}

	public CasoUsoPantallaId(int pantallaElementoid, int casoUsoElementoid) {
		this.pantallaElementoid = pantallaElementoid;
		this.casoUsoElementoid = casoUsoElementoid;
	}

	@Column(name = "PantallaElementoid", nullable = false)
	public int getPantallaElementoid() {
		return this.pantallaElementoid;
	}

	public void setPantallaElementoid(int pantallaElementoid) {
		this.pantallaElementoid = pantallaElementoid;
	}

	@Column(name = "CasoUsoElementoid", nullable = false)
	public int getCasoUsoElementoid() {
		return this.casoUsoElementoid;
	}

	public void setCasoUsoElementoid(int casoUsoElementoid) {
		this.casoUsoElementoid = casoUsoElementoid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CasoUsoPantallaId))
			return false;
		CasoUsoPantallaId castOther = (CasoUsoPantallaId) other;

		return (this.getPantallaElementoid() == castOther
				.getPantallaElementoid())
				&& (this.getCasoUsoElementoid() == castOther
						.getCasoUsoElementoid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPantallaElementoid();
		result = 37 * result + this.getCasoUsoElementoid();
		return result;
	}

}
