package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.PrimaryKeyJoinColumns;
import javax.persistence.Table;

import mx.prisma.admin.model.Proyecto;

/**
 * CasoUso generated by hbm2java
 */
@Entity
@Table(name = "CasoUso", catalog = "PRISMA")
@PrimaryKeyJoinColumns({
	@PrimaryKeyJoinColumn(name = "Elementoclave", referencedColumnName = "clave"),
	@PrimaryKeyJoinColumn(name = "Elementonumero", referencedColumnName = "numero"),
	@PrimaryKeyJoinColumn(name = "Elementonombre", referencedColumnName = "nombre") })
public class CasoUso extends Elemento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Modulo modulo;
	private Set<CasoUsoActor> actores = new HashSet<CasoUsoActor>(0);
	private Set<Salida> salidas = new HashSet<Salida>(0);
	private Set<Entrada> entradas = new HashSet<Entrada>(0);
	private Set<PostPrecondicion> postprecondiciones = new HashSet<PostPrecondicion>(0);
	private Set<Trayectoria> trayectorias = new HashSet<Trayectoria>(0);
	private Set<Extension> puntosExtension = new HashSet<Extension>(0);
	private Set<Extension> puntosExtiende = new HashSet<Extension>(0);
	private Set<Inclusion> incluidos = new HashSet<Inclusion>(0);
	private Set<Inclusion> incluye = new HashSet<Inclusion>(0);

	private Set<CasoUsoReglaNegocio> reglas = new HashSet<CasoUsoReglaNegocio>(0);



	private String redaccionActores;
	private String redaccionEntradas;
	private String redaccionSalidas;
	private String redaccionReglasNegocio;

	public CasoUso() {
	}

	public CasoUso(CasoUsoId id, EstadoElemento estadoElemento, Proyecto proyecto, String redaccionActores,
			String redaccionEntradas, String redaccionSalidas,
			String redaccionReglasNegocio, Modulo modulo) {
		super(new ElementoId(id.getElementoclave(), id.getElementonumero(), id.getElementonombre()), estadoElemento, proyecto);
		this.redaccionActores = redaccionActores;
		this.redaccionEntradas = redaccionEntradas;
		this.redaccionSalidas = redaccionSalidas;
		this.redaccionReglasNegocio = redaccionReglasNegocio;
		this.modulo = modulo;
	}

	@Column(name = "redaccionActores", length = 999)
	public String getRedaccionActores() {
		return this.redaccionActores;
	}

	public void setRedaccionActores(String redaccionActores) {
		this.redaccionActores = redaccionActores;
	}

	@Column(name = "redaccionEntradas", length = 999)
	public String getRedaccionEntradas() {
		return this.redaccionEntradas;
	}

	public void setRedaccionEntradas(String redaccionEntradas) {
		this.redaccionEntradas = redaccionEntradas;
	}

	@Column(name = "redaccionSalidas", length = 999)
	public String getRedaccionSalidas() {
		return this.redaccionSalidas;
	}

	public void setRedaccionSalidas(String redaccionSalidas) {
		this.redaccionSalidas = redaccionSalidas;
	}

	@Column(name = "redaccionReglasNegocio", length = 999)
	public String getRedaccionReglasNegocio() {
		return this.redaccionReglasNegocio;
	}

	public void setRedaccionReglasNegocio(String redaccionReglasNegocio) {
		this.redaccionReglasNegocio = redaccionReglasNegocio;
	}
	
	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "Moduloclave", referencedColumnName = "clave")
	public Modulo getModulo() {
		return modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.casodeuso", cascade = CascadeType.ALL)
	public Set<CasoUsoActor> getActores() {
		return actores;
	}

	public void setActores(Set<CasoUsoActor> actores) {
		this.actores = actores;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.casodeuso", cascade = CascadeType.ALL)
	public Set<Entrada> getEntradas() {
		return entradas;
	}

	public void setEntradas(Set<Entrada> entradas) {
		this.entradas = entradas;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.casodeuso", cascade = CascadeType.ALL)
	public Set<Salida> getSalidas() {
		return salidas;
	}
	
	public void setSalidas(Set<Salida> salidas) {
		this.salidas = salidas;
	}
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.casodeuso", cascade = CascadeType.ALL)
	public Set<PostPrecondicion> getPostPrecondiciones() {
		return postprecondiciones;
	}

	public void setPostPrecondiciones(Set<PostPrecondicion> postprecondiciones) {
		this.postprecondiciones = postprecondiciones;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.casodeuso", cascade = CascadeType.ALL)
	public Set<Trayectoria> getTrayectorias() {
		return trayectorias;
	}

	public void setTrayectorias(Set<Trayectoria> trayectorias) {
		this.trayectorias = trayectorias;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.casodeuso", cascade = CascadeType.ALL)
	public Set<Extension> getPuntosExtension() {
		return puntosExtension;
	}

	public void setPuntosExtension(Set<Extension> puntosExtension) {
		this.puntosExtension = puntosExtension;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.casodeuso_destino", cascade = CascadeType.ALL)	
	public Set<Extension> getPuntosExtiende() {
		return puntosExtiende;
	}

	public void setPuntosExtiende(Set<Extension> puntosExtiende) {
		this.puntosExtiende = puntosExtiende;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.casodeuso", cascade = CascadeType.ALL)
	public Set<Inclusion> getIncluidos() {
		return incluidos;
	}

	public void setIncluidos(Set<Inclusion> incluidos) {
		this.incluidos = incluidos;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.casodeuso_destino", cascade = CascadeType.ALL)
	public Set<Inclusion> getIncluye() {
		return incluye;
	}

	public void setIncluye(Set<Inclusion> incluye) {
		this.incluye = incluye;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.casodeuso", cascade = CascadeType.ALL)
	public Set<CasoUsoReglaNegocio> getReglas() {
		return reglas;
	}

	public void setReglas(Set<CasoUsoReglaNegocio> reglas) {
		this.reglas = reglas;
	}

}
