package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CasoUsoPantallaId generated by hbm2java
 */
@Embeddable
public class CasoUsoPantallaId implements java.io.Serializable {

	private String casoUsoElementoclave;
	private int casoUsoElementonumero;
	private String casoUsoElementonombre;
	private String casoUsoModuloclave;
	private String pantallaElementoclave;
	private int pantallaElementonumero;
	private String pantallaElementonombre;

	public CasoUsoPantallaId() {
	}

	public CasoUsoPantallaId(String casoUsoElementoclave,
			int casoUsoElementonumero, String casoUsoElementonombre,
			String casoUsoModuloclave, String pantallaElementoclave,
			int pantallaElementonumero, String pantallaElementonombre) {
		this.casoUsoElementoclave = casoUsoElementoclave;
		this.casoUsoElementonumero = casoUsoElementonumero;
		this.casoUsoElementonombre = casoUsoElementonombre;
		this.casoUsoModuloclave = casoUsoModuloclave;
		this.pantallaElementoclave = pantallaElementoclave;
		this.pantallaElementonumero = pantallaElementonumero;
		this.pantallaElementonombre = pantallaElementonombre;
	}

	@Column(name = "CasoUsoElementoclave", nullable = false, length = 10)
	public String getCasoUsoElementoclave() {
		return this.casoUsoElementoclave;
	}

	public void setCasoUsoElementoclave(String casoUsoElementoclave) {
		this.casoUsoElementoclave = casoUsoElementoclave;
	}

	@Column(name = "CasoUsoElementonumero", nullable = false)
	public int getCasoUsoElementonumero() {
		return this.casoUsoElementonumero;
	}

	public void setCasoUsoElementonumero(int casoUsoElementonumero) {
		this.casoUsoElementonumero = casoUsoElementonumero;
	}

	@Column(name = "CasoUsoElementonombre", nullable = false, length = 45)
	public String getCasoUsoElementonombre() {
		return this.casoUsoElementonombre;
	}

	public void setCasoUsoElementonombre(String casoUsoElementonombre) {
		this.casoUsoElementonombre = casoUsoElementonombre;
	}

	@Column(name = "CasoUsoModuloclave", nullable = false, length = 10)
	public String getCasoUsoModuloclave() {
		return this.casoUsoModuloclave;
	}

	public void setCasoUsoModuloclave(String casoUsoModuloclave) {
		this.casoUsoModuloclave = casoUsoModuloclave;
	}

	@Column(name = "PantallaElementoclave", nullable = false, length = 10)
	public String getPantallaElementoclave() {
		return this.pantallaElementoclave;
	}

	public void setPantallaElementoclave(String pantallaElementoclave) {
		this.pantallaElementoclave = pantallaElementoclave;
	}

	@Column(name = "PantallaElementonumero", nullable = false)
	public int getPantallaElementonumero() {
		return this.pantallaElementonumero;
	}

	public void setPantallaElementonumero(int pantallaElementonumero) {
		this.pantallaElementonumero = pantallaElementonumero;
	}

	@Column(name = "PantallaElementonombre", nullable = false, length = 45)
	public String getPantallaElementonombre() {
		return this.pantallaElementonombre;
	}

	public void setPantallaElementonombre(String pantallaElementonombre) {
		this.pantallaElementonombre = pantallaElementonombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CasoUsoPantallaId))
			return false;
		CasoUsoPantallaId castOther = (CasoUsoPantallaId) other;

		return ((this.getCasoUsoElementoclave() == castOther
				.getCasoUsoElementoclave()) || (this.getCasoUsoElementoclave() != null
				&& castOther.getCasoUsoElementoclave() != null && this
				.getCasoUsoElementoclave().equals(
						castOther.getCasoUsoElementoclave())))
				&& (this.getCasoUsoElementonumero() == castOther
						.getCasoUsoElementonumero())
				&& ((this.getCasoUsoElementonombre() == castOther
						.getCasoUsoElementonombre()) || (this
						.getCasoUsoElementonombre() != null
						&& castOther.getCasoUsoElementonombre() != null && this
						.getCasoUsoElementonombre().equals(
								castOther.getCasoUsoElementonombre())))
				&& ((this.getCasoUsoModuloclave() == castOther
						.getCasoUsoModuloclave()) || (this
						.getCasoUsoModuloclave() != null
						&& castOther.getCasoUsoModuloclave() != null && this
						.getCasoUsoModuloclave().equals(
								castOther.getCasoUsoModuloclave())))
				&& ((this.getPantallaElementoclave() == castOther
						.getPantallaElementoclave()) || (this
						.getPantallaElementoclave() != null
						&& castOther.getPantallaElementoclave() != null && this
						.getPantallaElementoclave().equals(
								castOther.getPantallaElementoclave())))
				&& (this.getPantallaElementonumero() == castOther
						.getPantallaElementonumero())
				&& ((this.getPantallaElementonombre() == castOther
						.getPantallaElementonombre()) || (this
						.getPantallaElementonombre() != null
						&& castOther.getPantallaElementonombre() != null && this
						.getPantallaElementonombre().equals(
								castOther.getPantallaElementonombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCasoUsoElementoclave() == null ? 0 : this
						.getCasoUsoElementoclave().hashCode());
		result = 37 * result + this.getCasoUsoElementonumero();
		result = 37
				* result
				+ (getCasoUsoElementonombre() == null ? 0 : this
						.getCasoUsoElementonombre().hashCode());
		result = 37
				* result
				+ (getCasoUsoModuloclave() == null ? 0 : this
						.getCasoUsoModuloclave().hashCode());
		result = 37
				* result
				+ (getPantallaElementoclave() == null ? 0 : this
						.getPantallaElementoclave().hashCode());
		result = 37 * result + this.getPantallaElementonumero();
		result = 37
				* result
				+ (getPantallaElementonombre() == null ? 0 : this
						.getPantallaElementonombre().hashCode());
		return result;
	}

}
