package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;

/**
 * CasoUsoReglaNegocioId generated by hbm2java
 */
@Embeddable
public class CasoUsoReglaNegocioId implements java.io.Serializable {

	private CasoUso casodeuso;
	private ReglaNegocio regladenegocio;


	public CasoUsoReglaNegocioId() {
	}

	public CasoUsoReglaNegocioId(CasoUso casodeuso, ReglaNegocio regladenegocio){
		this.casodeuso = casodeuso;
		this.regladenegocio = regladenegocio;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
        @JoinColumn(name = "CasoUsoElementoclave", referencedColumnName = "Elementoclave"),
        @JoinColumn(name = "CasoUsoElementonumero", referencedColumnName = "Elementonumero"),
        @JoinColumn(name = "CasoUsoElementonombre", referencedColumnName = "Elementonombre")
})
	public CasoUso getCasodeuso() {
		return casodeuso;
	}

	public void setCasodeuso(CasoUso casodeuso) {
		this.casodeuso = casodeuso;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
        @JoinColumn(name = "ReglaNegocioElementoclave", referencedColumnName = "Elementoclave"),
        @JoinColumn(name = "ReglaNegocioElementonumero", referencedColumnName = "Elementonumero"),
        @JoinColumn(name = "ReglaNegocioElementonombre", referencedColumnName = "Elementonombre")
})
	public ReglaNegocio getRegladenegocio() {
		return regladenegocio;
	}

	public void setRegladenegocio(ReglaNegocio regladenegocio) {
		this.regladenegocio = regladenegocio;
	}

	

}
