package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CasoUsoActor generated by hbm2java
 */
@Entity
@Table(name = "CasoUso_Actor", catalog = "PRISMA")
public class CasoUsoActor implements java.io.Serializable {

	private CasoUsoActorId id;

	public CasoUsoActor() {
	}

	public CasoUsoActor(CasoUsoActorId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numero", column = @Column(name = "numero", nullable = false)),
			@AttributeOverride(name = "casoUsoElementoclave", column = @Column(name = "CasoUsoElementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "casoUsoElementonumero", column = @Column(name = "CasoUsoElementonumero", nullable = false)),
			@AttributeOverride(name = "casoUsoElementonombre", column = @Column(name = "CasoUsoElementonombre", nullable = false, length = 45)),
			@AttributeOverride(name = "casoUsoModuloclave", column = @Column(name = "CasoUsoModuloclave", nullable = false, length = 10)),
			@AttributeOverride(name = "actorElementoclave", column = @Column(name = "ActorElementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "actorElementonumero", column = @Column(name = "ActorElementonumero", nullable = false)),
			@AttributeOverride(name = "actorElementonombre", column = @Column(name = "ActorElementonombre", nullable = false, length = 45)) })
	public CasoUsoActorId getId() {
		return this.id;
	}

	public void setId(CasoUsoActorId id) {
		this.id = id;
	}

}
