package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CasoUsoActorId generated by hbm2java
 */
@Embeddable
public class CasoUsoActorId implements java.io.Serializable {

	private int numero;
	private String casoUsoElementoclave;
	private int casoUsoElementonumero;
	private String casoUsoElementonombre;
	private String casoUsoModuloclave;
	private String actorElementoclave;
	private int actorElementonumero;
	private String actorElementonombre;

	public CasoUsoActorId() {
	}

	public CasoUsoActorId(int numero, String casoUsoElementoclave,
			int casoUsoElementonumero, String casoUsoElementonombre,
			String casoUsoModuloclave, String actorElementoclave,
			int actorElementonumero, String actorElementonombre) {
		this.numero = numero;
		this.casoUsoElementoclave = casoUsoElementoclave;
		this.casoUsoElementonumero = casoUsoElementonumero;
		this.casoUsoElementonombre = casoUsoElementonombre;
		this.casoUsoModuloclave = casoUsoModuloclave;
		this.actorElementoclave = actorElementoclave;
		this.actorElementonumero = actorElementonumero;
		this.actorElementonombre = actorElementonombre;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Column(name = "CasoUsoElementoclave", nullable = false, length = 10)
	public String getCasoUsoElementoclave() {
		return this.casoUsoElementoclave;
	}

	public void setCasoUsoElementoclave(String casoUsoElementoclave) {
		this.casoUsoElementoclave = casoUsoElementoclave;
	}

	@Column(name = "CasoUsoElementonumero", nullable = false)
	public int getCasoUsoElementonumero() {
		return this.casoUsoElementonumero;
	}

	public void setCasoUsoElementonumero(int casoUsoElementonumero) {
		this.casoUsoElementonumero = casoUsoElementonumero;
	}

	@Column(name = "CasoUsoElementonombre", nullable = false, length = 45)
	public String getCasoUsoElementonombre() {
		return this.casoUsoElementonombre;
	}

	public void setCasoUsoElementonombre(String casoUsoElementonombre) {
		this.casoUsoElementonombre = casoUsoElementonombre;
	}

	@Column(name = "CasoUsoModuloclave", nullable = false, length = 10)
	public String getCasoUsoModuloclave() {
		return this.casoUsoModuloclave;
	}

	public void setCasoUsoModuloclave(String casoUsoModuloclave) {
		this.casoUsoModuloclave = casoUsoModuloclave;
	}

	@Column(name = "ActorElementoclave", nullable = false, length = 10)
	public String getActorElementoclave() {
		return this.actorElementoclave;
	}

	public void setActorElementoclave(String actorElementoclave) {
		this.actorElementoclave = actorElementoclave;
	}

	@Column(name = "ActorElementonumero", nullable = false)
	public int getActorElementonumero() {
		return this.actorElementonumero;
	}

	public void setActorElementonumero(int actorElementonumero) {
		this.actorElementonumero = actorElementonumero;
	}

	@Column(name = "ActorElementonombre", nullable = false, length = 45)
	public String getActorElementonombre() {
		return this.actorElementonombre;
	}

	public void setActorElementonombre(String actorElementonombre) {
		this.actorElementonombre = actorElementonombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CasoUsoActorId))
			return false;
		CasoUsoActorId castOther = (CasoUsoActorId) other;

		return (this.getNumero() == castOther.getNumero())
				&& ((this.getCasoUsoElementoclave() == castOther
						.getCasoUsoElementoclave()) || (this
						.getCasoUsoElementoclave() != null
						&& castOther.getCasoUsoElementoclave() != null && this
						.getCasoUsoElementoclave().equals(
								castOther.getCasoUsoElementoclave())))
				&& (this.getCasoUsoElementonumero() == castOther
						.getCasoUsoElementonumero())
				&& ((this.getCasoUsoElementonombre() == castOther
						.getCasoUsoElementonombre()) || (this
						.getCasoUsoElementonombre() != null
						&& castOther.getCasoUsoElementonombre() != null && this
						.getCasoUsoElementonombre().equals(
								castOther.getCasoUsoElementonombre())))
				&& ((this.getCasoUsoModuloclave() == castOther
						.getCasoUsoModuloclave()) || (this
						.getCasoUsoModuloclave() != null
						&& castOther.getCasoUsoModuloclave() != null && this
						.getCasoUsoModuloclave().equals(
								castOther.getCasoUsoModuloclave())))
				&& ((this.getActorElementoclave() == castOther
						.getActorElementoclave()) || (this
						.getActorElementoclave() != null
						&& castOther.getActorElementoclave() != null && this
						.getActorElementoclave().equals(
								castOther.getActorElementoclave())))
				&& (this.getActorElementonumero() == castOther
						.getActorElementonumero())
				&& ((this.getActorElementonombre() == castOther
						.getActorElementonombre()) || (this
						.getActorElementonombre() != null
						&& castOther.getActorElementonombre() != null && this
						.getActorElementonombre().equals(
								castOther.getActorElementonombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumero();
		result = 37
				* result
				+ (getCasoUsoElementoclave() == null ? 0 : this
						.getCasoUsoElementoclave().hashCode());
		result = 37 * result + this.getCasoUsoElementonumero();
		result = 37
				* result
				+ (getCasoUsoElementonombre() == null ? 0 : this
						.getCasoUsoElementonombre().hashCode());
		result = 37
				* result
				+ (getCasoUsoModuloclave() == null ? 0 : this
						.getCasoUsoModuloclave().hashCode());
		result = 37
				* result
				+ (getActorElementoclave() == null ? 0 : this
						.getActorElementoclave().hashCode());
		result = 37 * result + this.getActorElementonumero();
		result = 37
				* result
				+ (getActorElementonombre() == null ? 0 : this
						.getActorElementonombre().hashCode());
		return result;
	}

}
