package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CasoUso generated by hbm2java
 */
@Entity
@Table(name = "CasoUso", catalog = "PRISMA")
public class CasoUso implements java.io.Serializable {

	private CasoUsoId id;
	private String redaccionActores;
	private String redaccionEntradas;
	private String redaccionSalidas;
	private String redaccionReglasNegocio;

	public CasoUso() {
	}

	public CasoUso(CasoUsoId id) {
		this.id = id;
	}

	public CasoUso(CasoUsoId id, String redaccionActores,
			String redaccionEntradas, String redaccionSalidas,
			String redaccionReglasNegocio) {
		this.id = id;
		this.redaccionActores = redaccionActores;
		this.redaccionEntradas = redaccionEntradas;
		this.redaccionSalidas = redaccionSalidas;
		this.redaccionReglasNegocio = redaccionReglasNegocio;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "elementoclave", column = @Column(name = "Elementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "elementonumero", column = @Column(name = "Elementonumero", nullable = false)),
			@AttributeOverride(name = "elementonombre", column = @Column(name = "Elementonombre", nullable = false, length = 45)),
			@AttributeOverride(name = "moduloclave", column = @Column(name = "Moduloclave", nullable = false, length = 10)) })
	public CasoUsoId getId() {
		return this.id;
	}

	public void setId(CasoUsoId id) {
		this.id = id;
	}

	@Column(name = "redaccionActores", length = 999)
	public String getRedaccionActores() {
		return this.redaccionActores;
	}

	public void setRedaccionActores(String redaccionActores) {
		this.redaccionActores = redaccionActores;
	}

	@Column(name = "redaccionEntradas", length = 999)
	public String getRedaccionEntradas() {
		return this.redaccionEntradas;
	}

	public void setRedaccionEntradas(String redaccionEntradas) {
		this.redaccionEntradas = redaccionEntradas;
	}

	@Column(name = "redaccionSalidas", length = 999)
	public String getRedaccionSalidas() {
		return this.redaccionSalidas;
	}

	public void setRedaccionSalidas(String redaccionSalidas) {
		this.redaccionSalidas = redaccionSalidas;
	}

	@Column(name = "redaccionReglasNegocio", length = 999)
	public String getRedaccionReglasNegocio() {
		return this.redaccionReglasNegocio;
	}

	public void setRedaccionReglasNegocio(String redaccionReglasNegocio) {
		this.redaccionReglasNegocio = redaccionReglasNegocio;
	}

}
