package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CasoUsoReglaNegocioId generated by hbm2java
 */
@Embeddable
public class CasoUsoReglaNegocioId implements java.io.Serializable {

	private String casoUsoElementoclave;
	private int casoUsoElementonumero;
	private String casoUsoElementonombre;
	private String casoUsoModuloclave;
	private String reglaNegocioElementoclave;
	private int reglaNegocioElementonumero;
	private String reglaNegocioElementonombre;

	public CasoUsoReglaNegocioId() {
	}

	public CasoUsoReglaNegocioId(String casoUsoElementoclave,
			int casoUsoElementonumero, String casoUsoElementonombre,
			String casoUsoModuloclave, String reglaNegocioElementoclave,
			int reglaNegocioElementonumero, String reglaNegocioElementonombre) {
		this.casoUsoElementoclave = casoUsoElementoclave;
		this.casoUsoElementonumero = casoUsoElementonumero;
		this.casoUsoElementonombre = casoUsoElementonombre;
		this.casoUsoModuloclave = casoUsoModuloclave;
		this.reglaNegocioElementoclave = reglaNegocioElementoclave;
		this.reglaNegocioElementonumero = reglaNegocioElementonumero;
		this.reglaNegocioElementonombre = reglaNegocioElementonombre;
	}

	@Column(name = "CasoUsoElementoclave", nullable = false, length = 10)
	public String getCasoUsoElementoclave() {
		return this.casoUsoElementoclave;
	}

	public void setCasoUsoElementoclave(String casoUsoElementoclave) {
		this.casoUsoElementoclave = casoUsoElementoclave;
	}

	@Column(name = "CasoUsoElementonumero", nullable = false)
	public int getCasoUsoElementonumero() {
		return this.casoUsoElementonumero;
	}

	public void setCasoUsoElementonumero(int casoUsoElementonumero) {
		this.casoUsoElementonumero = casoUsoElementonumero;
	}

	@Column(name = "CasoUsoElementonombre", nullable = false, length = 45)
	public String getCasoUsoElementonombre() {
		return this.casoUsoElementonombre;
	}

	public void setCasoUsoElementonombre(String casoUsoElementonombre) {
		this.casoUsoElementonombre = casoUsoElementonombre;
	}

	@Column(name = "CasoUsoModuloclave", nullable = false, length = 10)
	public String getCasoUsoModuloclave() {
		return this.casoUsoModuloclave;
	}

	public void setCasoUsoModuloclave(String casoUsoModuloclave) {
		this.casoUsoModuloclave = casoUsoModuloclave;
	}

	@Column(name = "ReglaNegocioElementoclave", nullable = false, length = 10)
	public String getReglaNegocioElementoclave() {
		return this.reglaNegocioElementoclave;
	}

	public void setReglaNegocioElementoclave(String reglaNegocioElementoclave) {
		this.reglaNegocioElementoclave = reglaNegocioElementoclave;
	}

	@Column(name = "ReglaNegocioElementonumero", nullable = false)
	public int getReglaNegocioElementonumero() {
		return this.reglaNegocioElementonumero;
	}

	public void setReglaNegocioElementonumero(int reglaNegocioElementonumero) {
		this.reglaNegocioElementonumero = reglaNegocioElementonumero;
	}

	@Column(name = "ReglaNegocioElementonombre", nullable = false, length = 45)
	public String getReglaNegocioElementonombre() {
		return this.reglaNegocioElementonombre;
	}

	public void setReglaNegocioElementonombre(String reglaNegocioElementonombre) {
		this.reglaNegocioElementonombre = reglaNegocioElementonombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CasoUsoReglaNegocioId))
			return false;
		CasoUsoReglaNegocioId castOther = (CasoUsoReglaNegocioId) other;

		return ((this.getCasoUsoElementoclave() == castOther
				.getCasoUsoElementoclave()) || (this.getCasoUsoElementoclave() != null
				&& castOther.getCasoUsoElementoclave() != null && this
				.getCasoUsoElementoclave().equals(
						castOther.getCasoUsoElementoclave())))
				&& (this.getCasoUsoElementonumero() == castOther
						.getCasoUsoElementonumero())
				&& ((this.getCasoUsoElementonombre() == castOther
						.getCasoUsoElementonombre()) || (this
						.getCasoUsoElementonombre() != null
						&& castOther.getCasoUsoElementonombre() != null && this
						.getCasoUsoElementonombre().equals(
								castOther.getCasoUsoElementonombre())))
				&& ((this.getCasoUsoModuloclave() == castOther
						.getCasoUsoModuloclave()) || (this
						.getCasoUsoModuloclave() != null
						&& castOther.getCasoUsoModuloclave() != null && this
						.getCasoUsoModuloclave().equals(
								castOther.getCasoUsoModuloclave())))
				&& ((this.getReglaNegocioElementoclave() == castOther
						.getReglaNegocioElementoclave()) || (this
						.getReglaNegocioElementoclave() != null
						&& castOther.getReglaNegocioElementoclave() != null && this
						.getReglaNegocioElementoclave().equals(
								castOther.getReglaNegocioElementoclave())))
				&& (this.getReglaNegocioElementonumero() == castOther
						.getReglaNegocioElementonumero())
				&& ((this.getReglaNegocioElementonombre() == castOther
						.getReglaNegocioElementonombre()) || (this
						.getReglaNegocioElementonombre() != null
						&& castOther.getReglaNegocioElementonombre() != null && this
						.getReglaNegocioElementonombre().equals(
								castOther.getReglaNegocioElementonombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCasoUsoElementoclave() == null ? 0 : this
						.getCasoUsoElementoclave().hashCode());
		result = 37 * result + this.getCasoUsoElementonumero();
		result = 37
				* result
				+ (getCasoUsoElementonombre() == null ? 0 : this
						.getCasoUsoElementonombre().hashCode());
		result = 37
				* result
				+ (getCasoUsoModuloclave() == null ? 0 : this
						.getCasoUsoModuloclave().hashCode());
		result = 37
				* result
				+ (getReglaNegocioElementoclave() == null ? 0 : this
						.getReglaNegocioElementoclave().hashCode());
		result = 37 * result + this.getReglaNegocioElementonumero();
		result = 37
				* result
				+ (getReglaNegocioElementonombre() == null ? 0 : this
						.getReglaNegocioElementonombre().hashCode());
		return result;
	}

}
