package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CasoUsoPantalla generated by hbm2java
 */
@Entity
@Table(name = "CasoUso_Pantalla", catalog = "PRISMA")
public class CasoUsoPantalla implements java.io.Serializable {

	private CasoUsoPantallaId id;

	public CasoUsoPantalla() {
	}

	public CasoUsoPantalla(CasoUsoPantallaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "casoUsoElementoclave", column = @Column(name = "CasoUsoElementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "casoUsoElementonumero", column = @Column(name = "CasoUsoElementonumero", nullable = false)),
			@AttributeOverride(name = "casoUsoElementonombre", column = @Column(name = "CasoUsoElementonombre", nullable = false, length = 45)),
			@AttributeOverride(name = "casoUsoModuloclave", column = @Column(name = "CasoUsoModuloclave", nullable = false, length = 10)),
			@AttributeOverride(name = "pantallaElementoclave", column = @Column(name = "PantallaElementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "pantallaElementonumero", column = @Column(name = "PantallaElementonumero", nullable = false)),
			@AttributeOverride(name = "pantallaElementonombre", column = @Column(name = "PantallaElementonombre", nullable = false, length = 45)) })
	public CasoUsoPantallaId getId() {
		return this.id;
	}

	public void setId(CasoUsoPantallaId id) {
		this.id = id;
	}

}
