package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CasoUsoActor generated by hbm2java
 */
@Entity
@Table(name = "CasoUso_Actor", catalog = "PRISMA")
public class CasoUsoActor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CasoUsoActorId id;

	public CasoUsoActor() {
	}

	public CasoUsoActor(CasoUsoActorId id) {
		this.id = id;
	}

	@EmbeddedId
	public CasoUsoActorId getId() {
		return this.id;
	}

	public void setId(CasoUsoActorId id) {
		this.id = id;
	}

}
