package mx.prisma.editor.model;

// Generated 07-jun-2015 17:10:34 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CasoUsoPantalla generated by hbm2java
 */
@Entity
@Table(name = "CasoUso_Pantalla", catalog = "PRISMA")
public class CasoUsoPantalla implements java.io.Serializable {

	private CasoUsoPantallaId id;
	private int numeroToken;

	public CasoUsoPantalla() {
	}

	public CasoUsoPantalla(CasoUsoPantallaId id, int numeroToken) {
		this.id = id;
		this.numeroToken = numeroToken;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pantallaElementoid", column = @Column(name = "PantallaElementoid", nullable = false)),
			@AttributeOverride(name = "casoUsoElementoid", column = @Column(name = "CasoUsoElementoid", nullable = false)) })
	public CasoUsoPantallaId getId() {
		return this.id;
	}

	public void setId(CasoUsoPantallaId id) {
		this.id = id;
	}

	@Column(name = "numeroToken", nullable = false)
	public int getNumeroToken() {
		return this.numeroToken;
	}

	public void setNumeroToken(int numeroToken) {
		this.numeroToken = numeroToken;
	}

}
