package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ElementoId generated by hbm2java
 */
@Embeddable
public class ElementoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String clave;
	private int numero;
	private String nombre;

	public ElementoId() {
	}

	public ElementoId(String clave, int numero, String nombre) {
		this.clave = clave;
		this.numero = numero;
		this.nombre = nombre;
	}

	@Column(name = "clave", nullable = false, length = 10)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ElementoId))
			return false;
		ElementoId castOther = (ElementoId) other;

		return ((this.getClave() == castOther.getClave()) || (this.getClave() != null
				&& castOther.getClave() != null && this.getClave().equals(
				castOther.getClave())))
				&& (this.getNumero() == castOther.getNumero())
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getClave() == null ? 0 : this.getClave().hashCode());
		result = 37 * result + this.getNumero();
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		return result;
	}

}
