package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.PrimaryKeyJoinColumns;
import javax.persistence.Table;

import mx.prisma.admin.model.Proyecto;

/**
 * Entidad generated by hbm2java
 */


@Entity
@Table(name = "Entidad", catalog = "PRISMA")
@PrimaryKeyJoinColumns({
	@PrimaryKeyJoinColumn(name = "Elementoclave", referencedColumnName = "clave"),
	@PrimaryKeyJoinColumn(name = "Elementonumero", referencedColumnName = "numero"),
	@PrimaryKeyJoinColumn(name = "Elementonombre", referencedColumnName = "nombre") })
public class Entidad extends Elemento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Set<Atributo> atributos = new HashSet<Atributo>(0);

	public Entidad() {
	}

	public Entidad(EntidadId id, EstadoElemento estadoElemento, Proyecto proyecto) {
		super(new ElementoId(id.getElementoclave(), id.getElementonumero(), id.getElementonombre()), estadoElemento, proyecto);
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idAtributo.entidad")
	public Set<Atributo> getAtributos() {
		return atributos;
	}

	public void setAtributos(Set<Atributo> atributos) {
		this.atributos = atributos;
	}

	
	
}
