package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Entrada generated by hbm2java
 */
@Entity
@Table(name = "Entrada", catalog = "PRISMA")
public class Entrada implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private EntradaId id;
	private Atributo atributo;
	private TerminoGlosario termino;

	public Entrada() {
	}

	public Entrada(EntradaId id) {
		this.id = id;
	}

	public Entrada(EntradaId id, Atributo atributo, TerminoGlosario termino) {
		this.id = id;
		this.atributo = atributo;
		this.termino = termino;

	}

	@EmbeddedId
	public EntradaId getId() {
		return this.id;
	}

	public void setId(EntradaId id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
        @JoinColumn(name = "AtributoEntidadElementoclave", referencedColumnName = "EntidadElementoclave"),
        @JoinColumn(name = "AtributoEntidadElementonumero", referencedColumnName = "EntidadElementonumero"),
        @JoinColumn(name = "AtributoEntidadElementonombre", referencedColumnName = "EntidadElementonombre"),
        @JoinColumn(name = "Atributonombre", referencedColumnName = "nombre")
})
	public Atributo getAtributo() {
		return atributo;
	}

	public void setAtributo(Atributo atributo) {
		this.atributo = atributo;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
        @JoinColumn(name = "TerminoGlosarioElementoclave", referencedColumnName = "Elementoclave"),
        @JoinColumn(name = "TerminoGlosarioElementonumero", referencedColumnName = "Elementonumero"),
        @JoinColumn(name = "TerminoGlosarioElementonombre", referencedColumnName = "Elementonombre")
})	
	public TerminoGlosario getTermino() {
		return termino;
	}

	public void setTermino(TerminoGlosario termino) {
		this.termino = termino;
	}

	

}
