package mx.prisma.editor.model;

// Generated 07-jun-2015 17:10:34 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Extension generated by hbm2java
 */
@Entity
@Table(name = "Extension", catalog = "PRISMA")
public class Extension implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ExtensionId id;
	private String causa;
	private String region;

	public Extension() {
	}

	public Extension(ExtensionId id, String causa, String region) {
		this.id = id;
		this.causa = causa;
		this.region = region;
	}

	@EmbeddedId
	public ExtensionId getId() {
		return this.id;
	}

	public void setId(ExtensionId id) {
		this.id = id;
	}

	@Column(name = "causa", nullable = false, length = 999)
	public String getCausa() {
		return this.causa;
	}

	public void setCausa(String causa) {
		this.causa = causa;
	}

	@Column(name = "region", nullable = false, length = 500)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

}
