package mx.prisma.editor.model;

// Generated 05-jun-2015 12:23:22 by Hibernate Tools 4.0.0

import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * ExtensionId generated by hbm2java
 */
@Embeddable
public class ExtensionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CasoUso casodeuso;
	private CasoUso casodeuso_destino;

	public ExtensionId() {
	}

	public ExtensionId(CasoUso casodeuso, CasoUso casodeuso_destino) {
		this.casodeuso = casodeuso;
		this.casodeuso_destino = casodeuso_destino;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
        @JoinColumn(name = "CasoUsoElementoclave", referencedColumnName = "Elementoclave"),
        @JoinColumn(name = "CasoUsoElementonumero", referencedColumnName = "Elementonumero"),
        @JoinColumn(name = "CasoUsoElementonombre", referencedColumnName = "Elementonombre")
})
	public CasoUso getCasodeuso() {
		return casodeuso;
	}

	public void setCasodeuso(CasoUso casodeuso) {
		this.casodeuso = casodeuso;
	}


	
	public CasoUso getCasodeuso_destino() {
		return casodeuso_destino;
	}

	public void setCasodeuso_destino(CasoUso casodeuso_destino) {
		this.casodeuso_destino = casodeuso_destino;
	}
	

}
