package mx.prisma.editor.model;

// Generated 05-jun-2015 12:23:22 by Hibernate Tools 4.0.0

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Inclusion generated by hbm2java
 */
@Entity
@Table(name = "Inclusion", catalog = "PRISMA")
public class Inclusion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private InclusionId id;

	public Inclusion() {
	}

	public Inclusion(InclusionId id) {
		this.id = id;
	}

	@EmbeddedId
	public InclusionId getId() {
		return this.id;
	}

	public void setId(InclusionId id) {
		this.id = id;
	}

}
