package mx.prisma.editor.model;

// Generated 07-jun-2015 17:10:34 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Inclusion generated by hbm2java
 */
@Entity
@Table(name = "Inclusion", catalog = "PRISMA")
public class Inclusion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private InclusionId id;

	public Inclusion() {
	}

	public Inclusion(InclusionId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "casoUsoElementoidOrigen", column = @Column(name = "CasoUsoElementoid_origen", nullable = false)),
			@AttributeOverride(name = "casoUsoElementoidDestino", column = @Column(name = "CasoUsoElementoid_destino", nullable = false)) })
	public InclusionId getId() {
		return this.id;
	}

	public void setId(InclusionId id) {
		this.id = id;
	}

}
