package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MensajeId generated by hbm2java
 */
@Embeddable
public class MensajeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String elementoclave;
	private int elementonumero;
	private String elementonombre;

	public MensajeId() {
	}

	public MensajeId(String elementoclave, int elementonumero,
			String elementonombre) {
		this.elementoclave = elementoclave;
		this.elementonumero = elementonumero;
		this.elementonombre = elementonombre;
	}

	@Column(name = "Elementoclave", nullable = false, length = 10)
	public String getElementoclave() {
		return this.elementoclave;
	}

	public void setElementoclave(String elementoclave) {
		this.elementoclave = elementoclave;
	}

	@Column(name = "Elementonumero", nullable = false)
	public int getElementonumero() {
		return this.elementonumero;
	}

	public void setElementonumero(int elementonumero) {
		this.elementonumero = elementonumero;
	}

	@Column(name = "Elementonombre", nullable = false, length = 45)
	public String getElementonombre() {
		return this.elementonombre;
	}

	public void setElementonombre(String elementonombre) {
		this.elementonombre = elementonombre;
	}

}
