package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MensajeTipoParametroMensajeId generated by hbm2java
 */
@Embeddable
public class MensajeTipoParametroMensajeId implements java.io.Serializable {

	private String mensajeElementoclave;
	private int mensajeElementonumero;
	private String mensajeElementonombre;
	private int tipoParametroidentificador;
	private int numeroParametro;

	public MensajeTipoParametroMensajeId() {
	}

	public MensajeTipoParametroMensajeId(String mensajeElementoclave,
			int mensajeElementonumero, String mensajeElementonombre,
			int tipoParametroidentificador, int numeroParametro) {
		this.mensajeElementoclave = mensajeElementoclave;
		this.mensajeElementonumero = mensajeElementonumero;
		this.mensajeElementonombre = mensajeElementonombre;
		this.tipoParametroidentificador = tipoParametroidentificador;
		this.numeroParametro = numeroParametro;
	}

	@Column(name = "MensajeElementoclave", nullable = false, length = 10)
	public String getMensajeElementoclave() {
		return this.mensajeElementoclave;
	}

	public void setMensajeElementoclave(String mensajeElementoclave) {
		this.mensajeElementoclave = mensajeElementoclave;
	}

	@Column(name = "MensajeElementonumero", nullable = false)
	public int getMensajeElementonumero() {
		return this.mensajeElementonumero;
	}

	public void setMensajeElementonumero(int mensajeElementonumero) {
		this.mensajeElementonumero = mensajeElementonumero;
	}

	@Column(name = "MensajeElementonombre", nullable = false, length = 45)
	public String getMensajeElementonombre() {
		return this.mensajeElementonombre;
	}

	public void setMensajeElementonombre(String mensajeElementonombre) {
		this.mensajeElementonombre = mensajeElementonombre;
	}

	@Column(name = "TipoParametroidentificador", nullable = false)
	public int getTipoParametroidentificador() {
		return this.tipoParametroidentificador;
	}

	public void setTipoParametroidentificador(int tipoParametroidentificador) {
		this.tipoParametroidentificador = tipoParametroidentificador;
	}

	@Column(name = "numeroParametro", nullable = false)
	public int getNumeroParametro() {
		return this.numeroParametro;
	}

	public void setNumeroParametro(int numeroParametro) {
		this.numeroParametro = numeroParametro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MensajeTipoParametroMensajeId))
			return false;
		MensajeTipoParametroMensajeId castOther = (MensajeTipoParametroMensajeId) other;

		return ((this.getMensajeElementoclave() == castOther
				.getMensajeElementoclave()) || (this.getMensajeElementoclave() != null
				&& castOther.getMensajeElementoclave() != null && this
				.getMensajeElementoclave().equals(
						castOther.getMensajeElementoclave())))
				&& (this.getMensajeElementonumero() == castOther
						.getMensajeElementonumero())
				&& ((this.getMensajeElementonombre() == castOther
						.getMensajeElementonombre()) || (this
						.getMensajeElementonombre() != null
						&& castOther.getMensajeElementonombre() != null && this
						.getMensajeElementonombre().equals(
								castOther.getMensajeElementonombre())))
				&& (this.getTipoParametroidentificador() == castOther
						.getTipoParametroidentificador())
				&& (this.getNumeroParametro() == castOther.getNumeroParametro());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getMensajeElementoclave() == null ? 0 : this
						.getMensajeElementoclave().hashCode());
		result = 37 * result + this.getMensajeElementonumero();
		result = 37
				* result
				+ (getMensajeElementonombre() == null ? 0 : this
						.getMensajeElementonombre().hashCode());
		result = 37 * result + this.getTipoParametroidentificador();
		result = 37 * result + this.getNumeroParametro();
		return result;
	}

}
