package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.PrimaryKeyJoinColumns;
import javax.persistence.Table;

import mx.prisma.admin.model.Proyecto;

/**
 * Mensaje generated by hbm2java
 */
@Entity
@Table(name = "Mensaje", catalog = "PRISMA")
@PrimaryKeyJoinColumns({
	@PrimaryKeyJoinColumn(name = "Elementoclave", referencedColumnName = "clave"),
	@PrimaryKeyJoinColumn(name = "Elementonumero", referencedColumnName = "numero"),
	@PrimaryKeyJoinColumn(name = "Elementonombre", referencedColumnName = "nombre") })
public class Mensaje extends Elemento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String redaccion;
	private boolean parametrizado;

	public Mensaje() {
	}

	public Mensaje(MensajeId id, EstadoElemento estadoElemento, Proyecto proyecto, String redaccion, boolean parametrizado) {
		super(new ElementoId(id.getElementoclave(), id.getElementonumero(), id.getElementonombre()), estadoElemento, proyecto);
		this.redaccion = redaccion;
		this.parametrizado = parametrizado;
	}

	@Column(name = "redaccion", nullable = false, length = 999)
	public String getRedaccion() {
		return this.redaccion;
	}

	public void setRedaccion(String redaccion) {
		this.redaccion = redaccion;
	}

	@Column(name = "parametrizado", nullable = false)
	public boolean isParametrizado() {
		return this.parametrizado;
	}

	public void setParametrizado(boolean parametrizado) {
		this.parametrizado = parametrizado;
	}

}
