package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MensajeTipoParametroMensaje generated by hbm2java
 */
@Entity
@Table(name = "Mensaje_TipoParametroMensaje", catalog = "PRISMA")
public class MensajeTipoParametroMensaje implements java.io.Serializable {

	private MensajeTipoParametroMensajeId id;
	private String otroValor;
	private String elementoclave;
	private Integer elementonumero;
	private String elementonombre;

	public MensajeTipoParametroMensaje() {
	}

	public MensajeTipoParametroMensaje(MensajeTipoParametroMensajeId id) {
		this.id = id;
	}

	public MensajeTipoParametroMensaje(MensajeTipoParametroMensajeId id,
			String otroValor, String elementoclave, Integer elementonumero,
			String elementonombre) {
		this.id = id;
		this.otroValor = otroValor;
		this.elementoclave = elementoclave;
		this.elementonumero = elementonumero;
		this.elementonombre = elementonombre;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "mensajeElementoclave", column = @Column(name = "MensajeElementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "mensajeElementonumero", column = @Column(name = "MensajeElementonumero", nullable = false)),
			@AttributeOverride(name = "mensajeElementonombre", column = @Column(name = "MensajeElementonombre", nullable = false, length = 45)),
			@AttributeOverride(name = "tipoParametroidentificador", column = @Column(name = "TipoParametroidentificador", nullable = false)),
			@AttributeOverride(name = "numeroParametro", column = @Column(name = "numeroParametro", nullable = false)) })
	public MensajeTipoParametroMensajeId getId() {
		return this.id;
	}

	public void setId(MensajeTipoParametroMensajeId id) {
		this.id = id;
	}

	@Column(name = "otroValor", length = 45)
	public String getOtroValor() {
		return this.otroValor;
	}

	public void setOtroValor(String otroValor) {
		this.otroValor = otroValor;
	}

	@Column(name = "Elementoclave", length = 10)
	public String getElementoclave() {
		return this.elementoclave;
	}

	public void setElementoclave(String elementoclave) {
		this.elementoclave = elementoclave;
	}

	@Column(name = "Elementonumero")
	public Integer getElementonumero() {
		return this.elementonumero;
	}

	public void setElementonumero(Integer elementonumero) {
		this.elementonumero = elementonumero;
	}

	@Column(name = "Elementonombre", length = 45)
	public String getElementonombre() {
		return this.elementonombre;
	}

	public void setElementonombre(String elementonombre) {
		this.elementonombre = elementonombre;
	}

}
