package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "Modulo", catalog = "PRISMA", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Modulo implements java.io.Serializable {

	private String clave;
	private String nombre;
	private String proyectoclave;
	private String descripcion;

	public Modulo() {
	}

	public Modulo(String clave, String nombre, String proyectoclave,
			String descripcion) {
		this.clave = clave;
		this.nombre = nombre;
		this.proyectoclave = proyectoclave;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "clave", unique = true, nullable = false, length = 10)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Proyectoclave", nullable = false, length = 10)
	public String getProyectoclave() {
		return this.proyectoclave;
	}

	public void setProyectoclave(String proyectoclave) {
		this.proyectoclave = proyectoclave;
	}

	@Column(name = "descripcion", nullable = false, length = 999)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
