package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Pantalla generated by hbm2java
 */
@Entity
@Table(name = "Pantalla", catalog = "PRISMA")
public class Pantalla implements java.io.Serializable {

	private PantallaId id;
	private String imagen;
	private String moduloclave;

	public Pantalla() {
	}

	public Pantalla(PantallaId id, String moduloclave) {
		this.id = id;
		this.moduloclave = moduloclave;
	}

	public Pantalla(PantallaId id, String imagen, String moduloclave) {
		this.id = id;
		this.imagen = imagen;
		this.moduloclave = moduloclave;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "elementoclave", column = @Column(name = "Elementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "elementonumero", column = @Column(name = "Elementonumero", nullable = false)),
			@AttributeOverride(name = "elementonombre", column = @Column(name = "Elementonombre", nullable = false, length = 45)) })
	public PantallaId getId() {
		return this.id;
	}

	public void setId(PantallaId id) {
		this.id = id;
	}

	@Column(name = "imagen", length = 999)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "Moduloclave", nullable = false, length = 10)
	public String getModuloclave() {
		return this.moduloclave;
	}

	public void setModuloclave(String moduloclave) {
		this.moduloclave = moduloclave;
	}

}
