package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Paso generated by hbm2java
 */
@Entity
@Table(name = "Paso", catalog = "PRISMA")
public class Paso implements java.io.Serializable {

	private PasoId id;
	private boolean realizaActor;
	private boolean finCasoUso;
	private String redaccion;

	public Paso() {
	}

	public Paso(PasoId id, boolean realizaActor, boolean finCasoUso,
			String redaccion) {
		this.id = id;
		this.realizaActor = realizaActor;
		this.finCasoUso = finCasoUso;
		this.redaccion = redaccion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numero", column = @Column(name = "numero", nullable = false)),
			@AttributeOverride(name = "trayectoriaidentificador", column = @Column(name = "Trayectoriaidentificador", nullable = false, length = 5)),
			@AttributeOverride(name = "trayectoriaCasoUsoElementoclave", column = @Column(name = "TrayectoriaCasoUsoElementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "trayectoriaCasoUsoElementonumero", column = @Column(name = "TrayectoriaCasoUsoElementonumero", nullable = false)),
			@AttributeOverride(name = "trayectoriaCasoUsoElementonombre", column = @Column(name = "TrayectoriaCasoUsoElementonombre", nullable = false, length = 45)),
			@AttributeOverride(name = "trayectoriaCasoUsoModuloclave", column = @Column(name = "TrayectoriaCasoUsoModuloclave", nullable = false, length = 10)) })
	public PasoId getId() {
		return this.id;
	}

	public void setId(PasoId id) {
		this.id = id;
	}

	@Column(name = "realizaActor", nullable = false)
	public boolean isRealizaActor() {
		return this.realizaActor;
	}

	public void setRealizaActor(boolean realizaActor) {
		this.realizaActor = realizaActor;
	}

	@Column(name = "finCasoUso", nullable = false)
	public boolean isFinCasoUso() {
		return this.finCasoUso;
	}

	public void setFinCasoUso(boolean finCasoUso) {
		this.finCasoUso = finCasoUso;
	}

	@Column(name = "redaccion", nullable = false, length = 999)
	public String getRedaccion() {
		return this.redaccion;
	}

	public void setRedaccion(String redaccion) {
		this.redaccion = redaccion;
	}

}
