package mx.prisma.editor.model;

// Generated 07-jun-2015 17:10:34 by Hibernate Tools 4.0.0

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Paso generated by hbm2java
 */
@Entity
@Table(name = "Paso", catalog = "PRISMA", uniqueConstraints = @UniqueConstraint(columnNames = {
		"numero", "Trayectoriaid" }))
public class Paso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int numero;
	private boolean realizaActor;
	private String redaccion;
	private Trayectoria trayectoria;

	public Paso() {
	}

	public Paso(int numero, boolean realizaActor, String redaccion,
			Trayectoria trayectoria) {
		this.numero = numero;
		this.realizaActor = realizaActor;
		this.redaccion = redaccion;
		this.trayectoria = trayectoria;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Column(name = "realizaActor", nullable = false)
	public boolean isRealizaActor() {
		return this.realizaActor;
	}

	public void setRealizaActor(boolean realizaActor) {
		this.realizaActor = realizaActor;
	}

	@Column(name = "redaccion", nullable = false, length = 999)
	public String getRedaccion() {
		return this.redaccion;
	}

	public void setRedaccion(String redaccion) {
		this.redaccion = redaccion;
	}
	
	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "Trayectoriaid", referencedColumnName = "id")
	public Trayectoria getTrayectoria() {
		return trayectoria;
	}

	public void setTrayectoria(Trayectoria trayectoria) {
		this.trayectoria = trayectoria;
	}



}
