package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;

/**
 * PasoId generated by hbm2java
 */
@Embeddable
public class PasoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numero;
	private Trayectoria trayectoria;

	public PasoId() {
	}

	public PasoId(int numero, Trayectoria trayectoria) {
		this.numero = numero;
		this.trayectoria = trayectoria;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
        @JoinColumn(name = "Trayectoriaidentificador", referencedColumnName = "identificador"),
        @JoinColumn(name = "TrayectoriaCasoUsoElementoclave", referencedColumnName = "CasoUsoElementoclave"),
        @JoinColumn(name = "TrayectoriaCasoUsoElementonumero", referencedColumnName = "CasoUsoElementonumero"),
        @JoinColumn(name = "TrayectoriaCasoUsoElementonombre", referencedColumnName = "CasoUsoElementonombre")

})
	public Trayectoria getTrayectoria() {
		return trayectoria;
	}

	public void setTrayectoria(Trayectoria trayectoria) {
		this.trayectoria = trayectoria;
	}
	
	

}
