package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Paso generated by hbm2java
 */
@Entity
@Table(name = "Paso", catalog = "PRISMA")
public class Paso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PasoId id;
	private boolean realizaActor;
	private boolean finCasoUso;
	private String redaccion;

	public Paso() {
	}

	public Paso(PasoId id, boolean realizaActor, boolean finCasoUso,
			String redaccion) {
		this.id = id;
		this.realizaActor = realizaActor;
		this.finCasoUso = finCasoUso;
		this.redaccion = redaccion;
	}

	@EmbeddedId
	public PasoId getId() {
		return this.id;
	}

	public void setId(PasoId id) {
		this.id = id;
	}

	@Column(name = "realizaActor", nullable = false)
	public boolean isRealizaActor() {
		return this.realizaActor;
	}

	public void setRealizaActor(boolean realizaActor) {
		this.realizaActor = realizaActor;
	}

	@Column(name = "finCasoUso", nullable = false)
	public boolean isFinCasoUso() {
		return this.finCasoUso;
	}

	public void setFinCasoUso(boolean finCasoUso) {
		this.finCasoUso = finCasoUso;
	}

	@Column(name = "redaccion", nullable = false, length = 999)
	public String getRedaccion() {
		return this.redaccion;
	}

	public void setRedaccion(String redaccion) {
		this.redaccion = redaccion;
	}

}
