package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PasoId generated by hbm2java
 */
@Embeddable
public class PasoId implements java.io.Serializable {

	private int numero;
	private String trayectoriaidentificador;
	private String trayectoriaCasoUsoElementoclave;
	private int trayectoriaCasoUsoElementonumero;
	private String trayectoriaCasoUsoElementonombre;
	private String trayectoriaCasoUsoModuloclave;

	public PasoId() {
	}

	public PasoId(int numero, String trayectoriaidentificador,
			String trayectoriaCasoUsoElementoclave,
			int trayectoriaCasoUsoElementonumero,
			String trayectoriaCasoUsoElementonombre,
			String trayectoriaCasoUsoModuloclave) {
		this.numero = numero;
		this.trayectoriaidentificador = trayectoriaidentificador;
		this.trayectoriaCasoUsoElementoclave = trayectoriaCasoUsoElementoclave;
		this.trayectoriaCasoUsoElementonumero = trayectoriaCasoUsoElementonumero;
		this.trayectoriaCasoUsoElementonombre = trayectoriaCasoUsoElementonombre;
		this.trayectoriaCasoUsoModuloclave = trayectoriaCasoUsoModuloclave;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Column(name = "Trayectoriaidentificador", nullable = false, length = 5)
	public String getTrayectoriaidentificador() {
		return this.trayectoriaidentificador;
	}

	public void setTrayectoriaidentificador(String trayectoriaidentificador) {
		this.trayectoriaidentificador = trayectoriaidentificador;
	}

	@Column(name = "TrayectoriaCasoUsoElementoclave", nullable = false, length = 10)
	public String getTrayectoriaCasoUsoElementoclave() {
		return this.trayectoriaCasoUsoElementoclave;
	}

	public void setTrayectoriaCasoUsoElementoclave(
			String trayectoriaCasoUsoElementoclave) {
		this.trayectoriaCasoUsoElementoclave = trayectoriaCasoUsoElementoclave;
	}

	@Column(name = "TrayectoriaCasoUsoElementonumero", nullable = false)
	public int getTrayectoriaCasoUsoElementonumero() {
		return this.trayectoriaCasoUsoElementonumero;
	}

	public void setTrayectoriaCasoUsoElementonumero(
			int trayectoriaCasoUsoElementonumero) {
		this.trayectoriaCasoUsoElementonumero = trayectoriaCasoUsoElementonumero;
	}

	@Column(name = "TrayectoriaCasoUsoElementonombre", nullable = false, length = 45)
	public String getTrayectoriaCasoUsoElementonombre() {
		return this.trayectoriaCasoUsoElementonombre;
	}

	public void setTrayectoriaCasoUsoElementonombre(
			String trayectoriaCasoUsoElementonombre) {
		this.trayectoriaCasoUsoElementonombre = trayectoriaCasoUsoElementonombre;
	}

	@Column(name = "TrayectoriaCasoUsoModuloclave", nullable = false, length = 10)
	public String getTrayectoriaCasoUsoModuloclave() {
		return this.trayectoriaCasoUsoModuloclave;
	}

	public void setTrayectoriaCasoUsoModuloclave(
			String trayectoriaCasoUsoModuloclave) {
		this.trayectoriaCasoUsoModuloclave = trayectoriaCasoUsoModuloclave;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PasoId))
			return false;
		PasoId castOther = (PasoId) other;

		return (this.getNumero() == castOther.getNumero())
				&& ((this.getTrayectoriaidentificador() == castOther
						.getTrayectoriaidentificador()) || (this
						.getTrayectoriaidentificador() != null
						&& castOther.getTrayectoriaidentificador() != null && this
						.getTrayectoriaidentificador().equals(
								castOther.getTrayectoriaidentificador())))
				&& ((this.getTrayectoriaCasoUsoElementoclave() == castOther
						.getTrayectoriaCasoUsoElementoclave()) || (this
						.getTrayectoriaCasoUsoElementoclave() != null
						&& castOther.getTrayectoriaCasoUsoElementoclave() != null && this
						.getTrayectoriaCasoUsoElementoclave().equals(
								castOther.getTrayectoriaCasoUsoElementoclave())))
				&& (this.getTrayectoriaCasoUsoElementonumero() == castOther
						.getTrayectoriaCasoUsoElementonumero())
				&& ((this.getTrayectoriaCasoUsoElementonombre() == castOther
						.getTrayectoriaCasoUsoElementonombre()) || (this
						.getTrayectoriaCasoUsoElementonombre() != null
						&& castOther.getTrayectoriaCasoUsoElementonombre() != null && this
						.getTrayectoriaCasoUsoElementonombre()
						.equals(castOther.getTrayectoriaCasoUsoElementonombre())))
				&& ((this.getTrayectoriaCasoUsoModuloclave() == castOther
						.getTrayectoriaCasoUsoModuloclave()) || (this
						.getTrayectoriaCasoUsoModuloclave() != null
						&& castOther.getTrayectoriaCasoUsoModuloclave() != null && this
						.getTrayectoriaCasoUsoModuloclave().equals(
								castOther.getTrayectoriaCasoUsoModuloclave())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumero();
		result = 37
				* result
				+ (getTrayectoriaidentificador() == null ? 0 : this
						.getTrayectoriaidentificador().hashCode());
		result = 37
				* result
				+ (getTrayectoriaCasoUsoElementoclave() == null ? 0 : this
						.getTrayectoriaCasoUsoElementoclave().hashCode());
		result = 37 * result + this.getTrayectoriaCasoUsoElementonumero();
		result = 37
				* result
				+ (getTrayectoriaCasoUsoElementonombre() == null ? 0 : this
						.getTrayectoriaCasoUsoElementonombre().hashCode());
		result = 37
				* result
				+ (getTrayectoriaCasoUsoModuloclave() == null ? 0 : this
						.getTrayectoriaCasoUsoModuloclave().hashCode());
		return result;
	}

}
