package mx.prisma.editor.model;

// Generated 07-jun-2015 17:10:34 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PostPrecondicion generated by hbm2java
 */
@Entity
@Table(name = "PostPrecondicion", catalog = "PRISMA")
public class PostPrecondicion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PostPrecondicionId id;
	private String redaccion;
	private boolean precondicion;

	public PostPrecondicion() {
	}

	public PostPrecondicion(PostPrecondicionId id, String redaccion,
			boolean precondicion) {
		this.id = id;
		this.redaccion = redaccion;
		this.precondicion = precondicion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "casoUsoElementoid", column = @Column(name = "CasoUsoElementoid", nullable = false)) })
	public PostPrecondicionId getId() {
		return this.id;
	}

	public void setId(PostPrecondicionId id) {
		this.id = id;
	}

	@Column(name = "redaccion", nullable = false, length = 999)
	public String getRedaccion() {
		return this.redaccion;
	}

	public void setRedaccion(String redaccion) {
		this.redaccion = redaccion;
	}

	@Column(name = "precondicion", nullable = false)
	public boolean isPrepost() {
		return this.precondicion;
	}

	public void setPrepost(boolean precondicion) {
		this.precondicion = precondicion;
	}

}
