package mx.prisma.editor.model;

// Generated 05-jun-2015 12:23:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PostPrecondicion generated by hbm2java
 */
@Entity
@Table(name = "PostPrecondicion", catalog = "PRISMA")
public class PostPrecondicion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PostPrecondicionId id;
	private String redaccion;
	private boolean prepost;
	private Set<ValorPrePostcondicion> valores= new HashSet<ValorPrePostcondicion>(0);

	public PostPrecondicion() {
	}

	public PostPrecondicion(PostPrecondicionId id, String redaccion) {
		this.id = id;
		this.redaccion = redaccion;
	}


	@EmbeddedId
	public PostPrecondicionId getId() {
		return this.id;
	}

	public void setId(PostPrecondicionId id) {
		this.id = id;
	}

	@Column(name = "redaccion", nullable = false, length = 999)
	public String getRedaccion() {
		return this.redaccion;
	}

	public void setRedaccion(String redaccion) {
		this.redaccion = redaccion;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.postPrecondicion", cascade = CascadeType.ALL)
	public Set<ValorPrePostcondicion> getValores() {
		return valores;
	}

	public void setValores(Set<ValorPrePostcondicion> valores) {
		this.valores = valores;
	}

	@Column(name = "prepost", nullable = false)
	public boolean isPrepost() {
		return prepost;
	}

	public void setPrepost(boolean prepost) {
		this.prepost = prepost;
	}

}
