package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ReglaNegocioTipoParametroReglaNegocio generated by hbm2java
 */
@Entity
@Table(name = "ReglaNegocio_TipoParametroReglaNegocio", catalog = "PRISMA")
public class ReglaNegocioTipoParametroReglaNegocio implements
		java.io.Serializable {

	private ReglaNegocioTipoParametroReglaNegocioId id;
	private Integer otroValor;
	private String elementoclave;
	private Integer elementonumero;
	private String elementonombre;

	public ReglaNegocioTipoParametroReglaNegocio() {
	}

	public ReglaNegocioTipoParametroReglaNegocio(
			ReglaNegocioTipoParametroReglaNegocioId id) {
		this.id = id;
	}

	public ReglaNegocioTipoParametroReglaNegocio(
			ReglaNegocioTipoParametroReglaNegocioId id, Integer otroValor,
			String elementoclave, Integer elementonumero, String elementonombre) {
		this.id = id;
		this.otroValor = otroValor;
		this.elementoclave = elementoclave;
		this.elementonumero = elementonumero;
		this.elementonombre = elementonombre;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numeroParametro", column = @Column(name = "numeroParametro", nullable = false)),
			@AttributeOverride(name = "reglaNegocioElementoclave", column = @Column(name = "ReglaNegocioElementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "reglaNegocioElementonumero", column = @Column(name = "ReglaNegocioElementonumero", nullable = false)),
			@AttributeOverride(name = "reglaNegocioElementonombre", column = @Column(name = "ReglaNegocioElementonombre", nullable = false, length = 45)),
			@AttributeOverride(name = "tipoParametroidentificador", column = @Column(name = "TipoParametroidentificador", nullable = false)) })
	public ReglaNegocioTipoParametroReglaNegocioId getId() {
		return this.id;
	}

	public void setId(ReglaNegocioTipoParametroReglaNegocioId id) {
		this.id = id;
	}

	@Column(name = "otroValor")
	public Integer getOtroValor() {
		return this.otroValor;
	}

	public void setOtroValor(Integer otroValor) {
		this.otroValor = otroValor;
	}

	@Column(name = "Elementoclave", length = 10)
	public String getElementoclave() {
		return this.elementoclave;
	}

	public void setElementoclave(String elementoclave) {
		this.elementoclave = elementoclave;
	}

	@Column(name = "Elementonumero")
	public Integer getElementonumero() {
		return this.elementonumero;
	}

	public void setElementonumero(Integer elementonumero) {
		this.elementonumero = elementonumero;
	}

	@Column(name = "Elementonombre", length = 45)
	public String getElementonombre() {
		return this.elementonombre;
	}

	public void setElementonombre(String elementonombre) {
		this.elementonombre = elementonombre;
	}

}
