package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ReglaNegocio generated by hbm2java
 */
@Entity
@Table(name = "ReglaNegocio", catalog = "PRISMA")
public class ReglaNegocio implements java.io.Serializable {

	private ReglaNegocioId id;
	private String redaccion;
	private int tipoReglaNegocioidentificador;

	public ReglaNegocio() {
	}

	public ReglaNegocio(ReglaNegocioId id, String redaccion,
			int tipoReglaNegocioidentificador) {
		this.id = id;
		this.redaccion = redaccion;
		this.tipoReglaNegocioidentificador = tipoReglaNegocioidentificador;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "elementoclave", column = @Column(name = "Elementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "elementonumero", column = @Column(name = "Elementonumero", nullable = false)),
			@AttributeOverride(name = "elementonombre", column = @Column(name = "Elementonombre", nullable = false, length = 45)) })
	public ReglaNegocioId getId() {
		return this.id;
	}

	public void setId(ReglaNegocioId id) {
		this.id = id;
	}

	@Column(name = "redaccion", nullable = false, length = 999)
	public String getRedaccion() {
		return this.redaccion;
	}

	public void setRedaccion(String redaccion) {
		this.redaccion = redaccion;
	}

	@Column(name = "TipoReglaNegocioidentificador", nullable = false)
	public int getTipoReglaNegocioidentificador() {
		return this.tipoReglaNegocioidentificador;
	}

	public void setTipoReglaNegocioidentificador(
			int tipoReglaNegocioidentificador) {
		this.tipoReglaNegocioidentificador = tipoReglaNegocioidentificador;
	}

}
