package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.PrimaryKeyJoinColumns;
import javax.persistence.Table;

import mx.prisma.admin.model.Proyecto;

/**
 * ReglaNegocio generated by hbm2java
 */
@Entity
@Table(name = "ReglaNegocio", catalog = "PRISMA")
@PrimaryKeyJoinColumns({
	@PrimaryKeyJoinColumn(name = "Elementoclave", referencedColumnName = "clave"),
	@PrimaryKeyJoinColumn(name = "Elementonumero", referencedColumnName = "numero"),
	@PrimaryKeyJoinColumn(name = "Elementonombre", referencedColumnName = "nombre") })
public class ReglaNegocio extends Elemento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String redaccion;
	private int tipoReglaNegocioidentificador;

	public ReglaNegocio() {
	}

	public ReglaNegocio(ReglaNegocioId id,  EstadoElemento estadoElemento, Proyecto proyecto, String redaccion,
			int tipoReglaNegocioidentificador) {
		this.redaccion = redaccion;
		this.tipoReglaNegocioidentificador = tipoReglaNegocioidentificador;
	}


	@Column(name = "redaccion", nullable = false, length = 999)
	public String getRedaccion() {
		return this.redaccion;
	}

	public void setRedaccion(String redaccion) {
		this.redaccion = redaccion;
	}

	@Column(name = "TipoReglaNegocioidentificador", nullable = false)
	public int getTipoReglaNegocioidentificador() {
		return this.tipoReglaNegocioidentificador;
	}

	public void setTipoReglaNegocioidentificador(
			int tipoReglaNegocioidentificador) {
		this.tipoReglaNegocioidentificador = tipoReglaNegocioidentificador;
	}

}
