package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReglaNegocioTipoParametroReglaNegocioId generated by hbm2java
 */
@Embeddable
public class ReglaNegocioTipoParametroReglaNegocioId implements
		java.io.Serializable {

	private int numeroParametro;
	private String reglaNegocioElementoclave;
	private int reglaNegocioElementonumero;
	private String reglaNegocioElementonombre;
	private int tipoParametroidentificador;

	public ReglaNegocioTipoParametroReglaNegocioId() {
	}

	public ReglaNegocioTipoParametroReglaNegocioId(int numeroParametro,
			String reglaNegocioElementoclave, int reglaNegocioElementonumero,
			String reglaNegocioElementonombre, int tipoParametroidentificador) {
		this.numeroParametro = numeroParametro;
		this.reglaNegocioElementoclave = reglaNegocioElementoclave;
		this.reglaNegocioElementonumero = reglaNegocioElementonumero;
		this.reglaNegocioElementonombre = reglaNegocioElementonombre;
		this.tipoParametroidentificador = tipoParametroidentificador;
	}

	@Column(name = "numeroParametro", nullable = false)
	public int getNumeroParametro() {
		return this.numeroParametro;
	}

	public void setNumeroParametro(int numeroParametro) {
		this.numeroParametro = numeroParametro;
	}

	@Column(name = "ReglaNegocioElementoclave", nullable = false, length = 10)
	public String getReglaNegocioElementoclave() {
		return this.reglaNegocioElementoclave;
	}

	public void setReglaNegocioElementoclave(String reglaNegocioElementoclave) {
		this.reglaNegocioElementoclave = reglaNegocioElementoclave;
	}

	@Column(name = "ReglaNegocioElementonumero", nullable = false)
	public int getReglaNegocioElementonumero() {
		return this.reglaNegocioElementonumero;
	}

	public void setReglaNegocioElementonumero(int reglaNegocioElementonumero) {
		this.reglaNegocioElementonumero = reglaNegocioElementonumero;
	}

	@Column(name = "ReglaNegocioElementonombre", nullable = false, length = 45)
	public String getReglaNegocioElementonombre() {
		return this.reglaNegocioElementonombre;
	}

	public void setReglaNegocioElementonombre(String reglaNegocioElementonombre) {
		this.reglaNegocioElementonombre = reglaNegocioElementonombre;
	}

	@Column(name = "TipoParametroidentificador", nullable = false)
	public int getTipoParametroidentificador() {
		return this.tipoParametroidentificador;
	}

	public void setTipoParametroidentificador(int tipoParametroidentificador) {
		this.tipoParametroidentificador = tipoParametroidentificador;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReglaNegocioTipoParametroReglaNegocioId))
			return false;
		ReglaNegocioTipoParametroReglaNegocioId castOther = (ReglaNegocioTipoParametroReglaNegocioId) other;

		return (this.getNumeroParametro() == castOther.getNumeroParametro())
				&& ((this.getReglaNegocioElementoclave() == castOther
						.getReglaNegocioElementoclave()) || (this
						.getReglaNegocioElementoclave() != null
						&& castOther.getReglaNegocioElementoclave() != null && this
						.getReglaNegocioElementoclave().equals(
								castOther.getReglaNegocioElementoclave())))
				&& (this.getReglaNegocioElementonumero() == castOther
						.getReglaNegocioElementonumero())
				&& ((this.getReglaNegocioElementonombre() == castOther
						.getReglaNegocioElementonombre()) || (this
						.getReglaNegocioElementonombre() != null
						&& castOther.getReglaNegocioElementonombre() != null && this
						.getReglaNegocioElementonombre().equals(
								castOther.getReglaNegocioElementonombre())))
				&& (this.getTipoParametroidentificador() == castOther
						.getTipoParametroidentificador());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumeroParametro();
		result = 37
				* result
				+ (getReglaNegocioElementoclave() == null ? 0 : this
						.getReglaNegocioElementoclave().hashCode());
		result = 37 * result + this.getReglaNegocioElementonumero();
		result = 37
				* result
				+ (getReglaNegocioElementonombre() == null ? 0 : this
						.getReglaNegocioElementonombre().hashCode());
		result = 37 * result + this.getTipoParametroidentificador();
		return result;
	}

}
