package mx.prisma.editor.model;

// Generated 07-jun-2015 17:10:34 by Hibernate Tools 4.0.0

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import mx.prisma.admin.model.Proyecto;

/**
 * ReglaNegocio generated by hbm2java
 */
@Entity
@Table(name = "ReglaNegocio", catalog = "PRISMA")
@PrimaryKeyJoinColumn(name = "Elementoid", referencedColumnName = "id")
public class ReglaNegocio extends Elemento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String redaccion;
	private TipoReglaNegocio tipoReglaNegocio;

	public ReglaNegocio() {
	}

	public ReglaNegocio(String clave, int numero, String nombre,
			Proyecto proyecto, String descripcion, EstadoElemento estadoElemento, String redaccion,
			TipoReglaNegocio tipoReglaNegocio) {
		super(clave, numero, nombre, proyecto, descripcion, estadoElemento);
		this.redaccion = redaccion;
		this.tipoReglaNegocio = tipoReglaNegocio;
	}

	@Column(name = "redaccion", nullable = false, length = 999)
	public String getRedaccion() {
		return this.redaccion;
	}

	public void setRedaccion(String redaccion) {
		this.redaccion = redaccion;
	}
	
	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "TipoReglaNegocioid", referencedColumnName = "id")
	public TipoReglaNegocio getTipoReglaNegocio() {
		return tipoReglaNegocio;
	}

	public void setTipoReglaNegocio(TipoReglaNegocio tipoReglaNegocio) {
		this.tipoReglaNegocio = tipoReglaNegocio;
	}



}
