package mx.prisma.editor.model;

// Generated 08-jun-2015 0:45:59 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Revision generated by hbm2java
 */
@Entity
@Table(name = "Revision", catalog = "PRISMA")
public class Revision implements java.io.Serializable {

	private Integer id;
	private String observaciones;
	private int casoUsoElementoid;
	private int seccionid;

	public Revision() {
	}

	public Revision(String observaciones, int casoUsoElementoid, int seccionid) {
		this.observaciones = observaciones;
		this.casoUsoElementoid = casoUsoElementoid;
		this.seccionid = seccionid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "observaciones", nullable = false, length = 999)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "CasoUsoElementoid", nullable = false)
	public int getCasoUsoElementoid() {
		return this.casoUsoElementoid;
	}

	public void setCasoUsoElementoid(int casoUsoElementoid) {
		this.casoUsoElementoid = casoUsoElementoid;
	}

	@Column(name = "Seccionid", nullable = false)
	public int getSeccionid() {
		return this.seccionid;
	}

	public void setSeccionid(int seccionid) {
		this.seccionid = seccionid;
	}

}
