package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RevisionId generated by hbm2java
 */
@Embeddable
public class RevisionId implements java.io.Serializable {

	private String casoUsoElementoclave;
	private int casoUsoElementonumero;
	private String casoUsoElementonombre;
	private int seccionidentififcador;
	private String casoUsoModuloclave;

	public RevisionId() {
	}

	public RevisionId(String casoUsoElementoclave, int casoUsoElementonumero,
			String casoUsoElementonombre, int seccionidentififcador,
			String casoUsoModuloclave) {
		this.casoUsoElementoclave = casoUsoElementoclave;
		this.casoUsoElementonumero = casoUsoElementonumero;
		this.casoUsoElementonombre = casoUsoElementonombre;
		this.seccionidentififcador = seccionidentififcador;
		this.casoUsoModuloclave = casoUsoModuloclave;
	}

	@Column(name = "CasoUsoElementoclave", nullable = false, length = 10)
	public String getCasoUsoElementoclave() {
		return this.casoUsoElementoclave;
	}

	public void setCasoUsoElementoclave(String casoUsoElementoclave) {
		this.casoUsoElementoclave = casoUsoElementoclave;
	}

	@Column(name = "CasoUsoElementonumero", nullable = false)
	public int getCasoUsoElementonumero() {
		return this.casoUsoElementonumero;
	}

	public void setCasoUsoElementonumero(int casoUsoElementonumero) {
		this.casoUsoElementonumero = casoUsoElementonumero;
	}

	@Column(name = "CasoUsoElementonombre", nullable = false, length = 45)
	public String getCasoUsoElementonombre() {
		return this.casoUsoElementonombre;
	}

	public void setCasoUsoElementonombre(String casoUsoElementonombre) {
		this.casoUsoElementonombre = casoUsoElementonombre;
	}

	@Column(name = "Seccionidentififcador", nullable = false)
	public int getSeccionidentififcador() {
		return this.seccionidentififcador;
	}

	public void setSeccionidentififcador(int seccionidentififcador) {
		this.seccionidentififcador = seccionidentififcador;
	}

	@Column(name = "CasoUsoModuloclave", nullable = false, length = 10)
	public String getCasoUsoModuloclave() {
		return this.casoUsoModuloclave;
	}

	public void setCasoUsoModuloclave(String casoUsoModuloclave) {
		this.casoUsoModuloclave = casoUsoModuloclave;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RevisionId))
			return false;
		RevisionId castOther = (RevisionId) other;

		return ((this.getCasoUsoElementoclave() == castOther
				.getCasoUsoElementoclave()) || (this.getCasoUsoElementoclave() != null
				&& castOther.getCasoUsoElementoclave() != null && this
				.getCasoUsoElementoclave().equals(
						castOther.getCasoUsoElementoclave())))
				&& (this.getCasoUsoElementonumero() == castOther
						.getCasoUsoElementonumero())
				&& ((this.getCasoUsoElementonombre() == castOther
						.getCasoUsoElementonombre()) || (this
						.getCasoUsoElementonombre() != null
						&& castOther.getCasoUsoElementonombre() != null && this
						.getCasoUsoElementonombre().equals(
								castOther.getCasoUsoElementonombre())))
				&& (this.getSeccionidentififcador() == castOther
						.getSeccionidentififcador())
				&& ((this.getCasoUsoModuloclave() == castOther
						.getCasoUsoModuloclave()) || (this
						.getCasoUsoModuloclave() != null
						&& castOther.getCasoUsoModuloclave() != null && this
						.getCasoUsoModuloclave().equals(
								castOther.getCasoUsoModuloclave())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCasoUsoElementoclave() == null ? 0 : this
						.getCasoUsoElementoclave().hashCode());
		result = 37 * result + this.getCasoUsoElementonumero();
		result = 37
				* result
				+ (getCasoUsoElementonombre() == null ? 0 : this
						.getCasoUsoElementonombre().hashCode());
		result = 37 * result + this.getSeccionidentififcador();
		result = 37
				* result
				+ (getCasoUsoModuloclave() == null ? 0 : this
						.getCasoUsoModuloclave().hashCode());
		return result;
	}

}
