package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Revision generated by hbm2java
 */
@Entity
@Table(name = "Revision", catalog = "PRISMA")
public class Revision implements java.io.Serializable {

	private RevisionId id;
	private String observaciones;

	public Revision() {
	}

	public Revision(RevisionId id) {
		this.id = id;
	}

	public Revision(RevisionId id, String observaciones) {
		this.id = id;
		this.observaciones = observaciones;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "casoUsoElementoclave", column = @Column(name = "CasoUsoElementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "casoUsoElementonumero", column = @Column(name = "CasoUsoElementonumero", nullable = false)),
			@AttributeOverride(name = "casoUsoElementonombre", column = @Column(name = "CasoUsoElementonombre", nullable = false, length = 45)),
			@AttributeOverride(name = "seccionidentififcador", column = @Column(name = "Seccionidentififcador", nullable = false)),
			@AttributeOverride(name = "casoUsoModuloclave", column = @Column(name = "CasoUsoModuloclave", nullable = false, length = 10)) })
	public RevisionId getId() {
		return this.id;
	}

	public void setId(RevisionId id) {
		this.id = id;
	}

	@Column(name = "Observaciones", length = 999)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
