package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Salida generated by hbm2java
 */
@Entity
@Table(name = "Salida", catalog = "PRISMA", uniqueConstraints = {
		@UniqueConstraint(columnNames = "AtributoEntidadElementonumero"),
		@UniqueConstraint(columnNames = "CasoUsoElementonombre"),
		@UniqueConstraint(columnNames = "MensajeElementoclave"),
		@UniqueConstraint(columnNames = "MensajeElementonombre"),
		@UniqueConstraint(columnNames = "TerminoGlosarioElementoclave"),
		@UniqueConstraint(columnNames = "AtributoEntidadElementoclave"),
		@UniqueConstraint(columnNames = "AtributoEntidadElementonombre"),
		@UniqueConstraint(columnNames = "TerminoGlosarioElementonumero"),
		@UniqueConstraint(columnNames = "MensajeElementonumero"),
		@UniqueConstraint(columnNames = "TerminoGlosarioElementonombre"),
		@UniqueConstraint(columnNames = "CasoUsoElementoclave"),
		@UniqueConstraint(columnNames = "Atributonombre"),
		@UniqueConstraint(columnNames = "CasoUsoElementonumero") })
public class Salida implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private SalidaId id;
	private Mensaje mensaje;
	private Atributo atributo;
	private TerminoGlosario termino;
	

	public Salida() {
	}

	public Salida(SalidaId id) {
		this.id = id;
	}

	public Salida(SalidaId id, Mensaje mensaje) {
		this.id = id;
	}
	public Salida(SalidaId id, Atributo atributo) {
		this.id = id;
	}
	public Salida(SalidaId id, TerminoGlosario termino) {
		this.id = id;
	}

	@EmbeddedId
	public SalidaId getId() {
		return this.id;
	}

	public void setId(SalidaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
        @JoinColumn(name = "MensajeElementoclave", referencedColumnName = "Elementoclave"),
        @JoinColumn(name = "MensajeElementonumero", referencedColumnName = "Elementonumero"),
        @JoinColumn(name = "MensajeElementonombre", referencedColumnName = "Elementonombre")
})	
	public Mensaje getMensaje() {
		return mensaje;
	}

	public void setMensaje(Mensaje mensaje) {
		this.mensaje = mensaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
        @JoinColumn(name = "AtributoEntidadElementoclave", referencedColumnName = "EntidadElementoclave"),
        @JoinColumn(name = "AtributoEntidadElementonumero", referencedColumnName = "EntidadElementonumero"),
        @JoinColumn(name = "AtributoEntidadElementonombre", referencedColumnName = "EntidadElementonombre"),
        @JoinColumn(name = "Atributonombre", referencedColumnName = "nombre")
})	
	public Atributo getAtributo() {
		return atributo;
	}

	public void setAtributo(Atributo atributo) {
		this.atributo = atributo;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
        @JoinColumn(name = "TerminoGlosarioElementoclave", referencedColumnName = "Elementoclave"),
        @JoinColumn(name = "TerminoGlosarioElementonumero", referencedColumnName = "Elementonumero"),
        @JoinColumn(name = "TerminoGlosarioElementonombre", referencedColumnName = "Elementonombre")
})	
	public TerminoGlosario getTermino() {
		return termino;
	}

	public void setTermino(TerminoGlosario termino) {
		this.termino = termino;
	}

	

}
