package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TerminoGlosario generated by hbm2java
 */
@Entity
@Table(name = "TerminoGlosario", catalog = "PRISMA")
public class TerminoGlosario implements java.io.Serializable {

	private TerminoGlosarioId id;

	public TerminoGlosario() {
	}

	public TerminoGlosario(TerminoGlosarioId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "elementoclave", column = @Column(name = "Elementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "elementonumero", column = @Column(name = "Elementonumero", nullable = false)),
			@AttributeOverride(name = "elementonombre", column = @Column(name = "Elementonombre", nullable = false, length = 45)) })
	public TerminoGlosarioId getId() {
		return this.id;
	}

	public void setId(TerminoGlosarioId id) {
		this.id = id;
	}

}
