package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trayectoria generated by hbm2java
 */
@Entity
@Table(name = "Trayectoria", catalog = "PRISMA")
public class Trayectoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TrayectoriaId id;
	private boolean alternativa;
	private String condicion;
	private Set<Paso> pasos = new HashSet<Paso>(0);


	public Trayectoria() {
	}

	public Trayectoria(TrayectoriaId id, boolean alternativa) {
		this.id = id;
		this.alternativa = alternativa;
	}

	public Trayectoria(TrayectoriaId id, boolean alternativa, String condicion) {
		this.id = id;
		this.alternativa = alternativa;
		this.condicion = condicion;
	}

	@EmbeddedId
	public TrayectoriaId getId() {
		return this.id;
	}

	public void setId(TrayectoriaId id) {
		this.id = id;
	}

	@Column(name = "alternativa", nullable = false)
	public boolean isAlternativa() {
		return this.alternativa;
	}

	public void setAlternativa(boolean alternativa) {
		this.alternativa = alternativa;
	}

	@Column(name = "condicion", length = 999)
	public String getCondicion() {
		return this.condicion;
	}

	public void setCondicion(String condicion) {
		this.condicion = condicion;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "id.trayectoria", cascade = CascadeType.ALL)
	public Set<Paso> getPasos() {
		return pasos;
	}

	public void setPasos(Set<Paso> pasos) {
		this.pasos = pasos;
	}

}
