package mx.prisma.editor.model;

// Generated 29-may-2015 2:01:49 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Trayectoria generated by hbm2java
 */
@Entity
@Table(name = "Trayectoria", catalog = "PRISMA")
public class Trayectoria implements java.io.Serializable {

	private TrayectoriaId id;
	private boolean alternativa;
	private String condicion;

	public Trayectoria() {
	}

	public Trayectoria(TrayectoriaId id, boolean alternativa) {
		this.id = id;
		this.alternativa = alternativa;
	}

	public Trayectoria(TrayectoriaId id, boolean alternativa, String condicion) {
		this.id = id;
		this.alternativa = alternativa;
		this.condicion = condicion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "identificador", column = @Column(name = "identificador", nullable = false, length = 5)),
			@AttributeOverride(name = "casoUsoElementoclave", column = @Column(name = "CasoUsoElementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "casoUsoElementonumero", column = @Column(name = "CasoUsoElementonumero", nullable = false)),
			@AttributeOverride(name = "casoUsoElementonombre", column = @Column(name = "CasoUsoElementonombre", nullable = false, length = 45)),
			@AttributeOverride(name = "casoUsoModuloclave", column = @Column(name = "CasoUsoModuloclave", nullable = false, length = 10)) })
	public TrayectoriaId getId() {
		return this.id;
	}

	public void setId(TrayectoriaId id) {
		this.id = id;
	}

	@Column(name = "alternativa", nullable = false)
	public boolean isAlternativa() {
		return this.alternativa;
	}

	public void setAlternativa(boolean alternativa) {
		this.alternativa = alternativa;
	}

	@Column(name = "condicion", length = 999)
	public String getCondicion() {
		return this.condicion;
	}

	public void setCondicion(String condicion) {
		this.condicion = condicion;
	}

}
