package mx.prisma.editor.model;

// Generated 05-jun-2015 12:23:22 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ValorParametroExtensionId generated by hbm2java
 */
@Embeddable
public class ValorParametroExtensionId implements java.io.Serializable {

	private String extensionCasoUsoclaveOrigen;
	private int extensionCasoUsonumeroOrigen;
	private String extensionCasoUsonombreOrigen;
	private String extensionCasoUsoModuloclaveOrigen;
	private String extensionCasoUsoclaveDestino;
	private int extensionCasoUsonumeroDestino;
	private String extensionCasoUsonombreDestino;
	private String extensionCasoUsoModuloclaveDestino;
	private int pasonumero;
	private String pasoTrayectoriaidentificador;
	private String pasoTrayectoriaCasoUsoElementoclave;
	private int pasoTrayectoriaCasoUsoElementonumero;
	private String pasoTrayectoriaCasoUsoElementonombre;
	private String pasoTrayectoriaCasoUsoModuloclave;

	public ValorParametroExtensionId() {
	}

	public ValorParametroExtensionId(String extensionCasoUsoclaveOrigen,
			int extensionCasoUsonumeroOrigen,
			String extensionCasoUsonombreOrigen,
			String extensionCasoUsoModuloclaveOrigen,
			String extensionCasoUsoclaveDestino,
			int extensionCasoUsonumeroDestino,
			String extensionCasoUsonombreDestino,
			String extensionCasoUsoModuloclaveDestino, int pasonumero,
			String pasoTrayectoriaidentificador,
			String pasoTrayectoriaCasoUsoElementoclave,
			int pasoTrayectoriaCasoUsoElementonumero,
			String pasoTrayectoriaCasoUsoElementonombre,
			String pasoTrayectoriaCasoUsoModuloclave) {
		this.extensionCasoUsoclaveOrigen = extensionCasoUsoclaveOrigen;
		this.extensionCasoUsonumeroOrigen = extensionCasoUsonumeroOrigen;
		this.extensionCasoUsonombreOrigen = extensionCasoUsonombreOrigen;
		this.extensionCasoUsoModuloclaveOrigen = extensionCasoUsoModuloclaveOrigen;
		this.extensionCasoUsoclaveDestino = extensionCasoUsoclaveDestino;
		this.extensionCasoUsonumeroDestino = extensionCasoUsonumeroDestino;
		this.extensionCasoUsonombreDestino = extensionCasoUsonombreDestino;
		this.extensionCasoUsoModuloclaveDestino = extensionCasoUsoModuloclaveDestino;
		this.pasonumero = pasonumero;
		this.pasoTrayectoriaidentificador = pasoTrayectoriaidentificador;
		this.pasoTrayectoriaCasoUsoElementoclave = pasoTrayectoriaCasoUsoElementoclave;
		this.pasoTrayectoriaCasoUsoElementonumero = pasoTrayectoriaCasoUsoElementonumero;
		this.pasoTrayectoriaCasoUsoElementonombre = pasoTrayectoriaCasoUsoElementonombre;
		this.pasoTrayectoriaCasoUsoModuloclave = pasoTrayectoriaCasoUsoModuloclave;
	}

	@Column(name = "ExtensionCasoUsoclave_origen", nullable = false, length = 10)
	public String getExtensionCasoUsoclaveOrigen() {
		return this.extensionCasoUsoclaveOrigen;
	}

	public void setExtensionCasoUsoclaveOrigen(
			String extensionCasoUsoclaveOrigen) {
		this.extensionCasoUsoclaveOrigen = extensionCasoUsoclaveOrigen;
	}

	@Column(name = "ExtensionCasoUsonumero_origen", nullable = false)
	public int getExtensionCasoUsonumeroOrigen() {
		return this.extensionCasoUsonumeroOrigen;
	}

	public void setExtensionCasoUsonumeroOrigen(int extensionCasoUsonumeroOrigen) {
		this.extensionCasoUsonumeroOrigen = extensionCasoUsonumeroOrigen;
	}

	@Column(name = "ExtensionCasoUsonombre_origen", nullable = false, length = 45)
	public String getExtensionCasoUsonombreOrigen() {
		return this.extensionCasoUsonombreOrigen;
	}

	public void setExtensionCasoUsonombreOrigen(
			String extensionCasoUsonombreOrigen) {
		this.extensionCasoUsonombreOrigen = extensionCasoUsonombreOrigen;
	}

	@Column(name = "ExtensionCasoUsoModuloclave_origen", nullable = false, length = 10)
	public String getExtensionCasoUsoModuloclaveOrigen() {
		return this.extensionCasoUsoModuloclaveOrigen;
	}

	public void setExtensionCasoUsoModuloclaveOrigen(
			String extensionCasoUsoModuloclaveOrigen) {
		this.extensionCasoUsoModuloclaveOrigen = extensionCasoUsoModuloclaveOrigen;
	}

	@Column(name = "ExtensionCasoUsoclave_destino", nullable = false, length = 10)
	public String getExtensionCasoUsoclaveDestino() {
		return this.extensionCasoUsoclaveDestino;
	}

	public void setExtensionCasoUsoclaveDestino(
			String extensionCasoUsoclaveDestino) {
		this.extensionCasoUsoclaveDestino = extensionCasoUsoclaveDestino;
	}

	@Column(name = "ExtensionCasoUsonumero_destino", nullable = false)
	public int getExtensionCasoUsonumeroDestino() {
		return this.extensionCasoUsonumeroDestino;
	}

	public void setExtensionCasoUsonumeroDestino(
			int extensionCasoUsonumeroDestino) {
		this.extensionCasoUsonumeroDestino = extensionCasoUsonumeroDestino;
	}

	@Column(name = "ExtensionCasoUsonombre_destino", nullable = false, length = 45)
	public String getExtensionCasoUsonombreDestino() {
		return this.extensionCasoUsonombreDestino;
	}

	public void setExtensionCasoUsonombreDestino(
			String extensionCasoUsonombreDestino) {
		this.extensionCasoUsonombreDestino = extensionCasoUsonombreDestino;
	}

	@Column(name = "ExtensionCasoUsoModuloclave_destino", nullable = false, length = 10)
	public String getExtensionCasoUsoModuloclaveDestino() {
		return this.extensionCasoUsoModuloclaveDestino;
	}

	public void setExtensionCasoUsoModuloclaveDestino(
			String extensionCasoUsoModuloclaveDestino) {
		this.extensionCasoUsoModuloclaveDestino = extensionCasoUsoModuloclaveDestino;
	}

	@Column(name = "Pasonumero", nullable = false)
	public int getPasonumero() {
		return this.pasonumero;
	}

	public void setPasonumero(int pasonumero) {
		this.pasonumero = pasonumero;
	}

	@Column(name = "PasoTrayectoriaidentificador", nullable = false, length = 5)
	public String getPasoTrayectoriaidentificador() {
		return this.pasoTrayectoriaidentificador;
	}

	public void setPasoTrayectoriaidentificador(
			String pasoTrayectoriaidentificador) {
		this.pasoTrayectoriaidentificador = pasoTrayectoriaidentificador;
	}

	@Column(name = "PasoTrayectoriaCasoUsoElementoclave", nullable = false, length = 10)
	public String getPasoTrayectoriaCasoUsoElementoclave() {
		return this.pasoTrayectoriaCasoUsoElementoclave;
	}

	public void setPasoTrayectoriaCasoUsoElementoclave(
			String pasoTrayectoriaCasoUsoElementoclave) {
		this.pasoTrayectoriaCasoUsoElementoclave = pasoTrayectoriaCasoUsoElementoclave;
	}

	@Column(name = "PasoTrayectoriaCasoUsoElementonumero", nullable = false)
	public int getPasoTrayectoriaCasoUsoElementonumero() {
		return this.pasoTrayectoriaCasoUsoElementonumero;
	}

	public void setPasoTrayectoriaCasoUsoElementonumero(
			int pasoTrayectoriaCasoUsoElementonumero) {
		this.pasoTrayectoriaCasoUsoElementonumero = pasoTrayectoriaCasoUsoElementonumero;
	}

	@Column(name = "PasoTrayectoriaCasoUsoElementonombre", nullable = false, length = 45)
	public String getPasoTrayectoriaCasoUsoElementonombre() {
		return this.pasoTrayectoriaCasoUsoElementonombre;
	}

	public void setPasoTrayectoriaCasoUsoElementonombre(
			String pasoTrayectoriaCasoUsoElementonombre) {
		this.pasoTrayectoriaCasoUsoElementonombre = pasoTrayectoriaCasoUsoElementonombre;
	}

	@Column(name = "PasoTrayectoriaCasoUsoModuloclave", nullable = false, length = 10)
	public String getPasoTrayectoriaCasoUsoModuloclave() {
		return this.pasoTrayectoriaCasoUsoModuloclave;
	}

	public void setPasoTrayectoriaCasoUsoModuloclave(
			String pasoTrayectoriaCasoUsoModuloclave) {
		this.pasoTrayectoriaCasoUsoModuloclave = pasoTrayectoriaCasoUsoModuloclave;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ValorParametroExtensionId))
			return false;
		ValorParametroExtensionId castOther = (ValorParametroExtensionId) other;

		return ((this.getExtensionCasoUsoclaveOrigen() == castOther
				.getExtensionCasoUsoclaveOrigen()) || (this
				.getExtensionCasoUsoclaveOrigen() != null
				&& castOther.getExtensionCasoUsoclaveOrigen() != null && this
				.getExtensionCasoUsoclaveOrigen().equals(
						castOther.getExtensionCasoUsoclaveOrigen())))
				&& (this.getExtensionCasoUsonumeroOrigen() == castOther
						.getExtensionCasoUsonumeroOrigen())
				&& ((this.getExtensionCasoUsonombreOrigen() == castOther
						.getExtensionCasoUsonombreOrigen()) || (this
						.getExtensionCasoUsonombreOrigen() != null
						&& castOther.getExtensionCasoUsonombreOrigen() != null && this
						.getExtensionCasoUsonombreOrigen().equals(
								castOther.getExtensionCasoUsonombreOrigen())))
				&& ((this.getExtensionCasoUsoModuloclaveOrigen() == castOther
						.getExtensionCasoUsoModuloclaveOrigen()) || (this
						.getExtensionCasoUsoModuloclaveOrigen() != null
						&& castOther.getExtensionCasoUsoModuloclaveOrigen() != null && this
						.getExtensionCasoUsoModuloclaveOrigen()
						.equals(castOther
								.getExtensionCasoUsoModuloclaveOrigen())))
				&& ((this.getExtensionCasoUsoclaveDestino() == castOther
						.getExtensionCasoUsoclaveDestino()) || (this
						.getExtensionCasoUsoclaveDestino() != null
						&& castOther.getExtensionCasoUsoclaveDestino() != null && this
						.getExtensionCasoUsoclaveDestino().equals(
								castOther.getExtensionCasoUsoclaveDestino())))
				&& (this.getExtensionCasoUsonumeroDestino() == castOther
						.getExtensionCasoUsonumeroDestino())
				&& ((this.getExtensionCasoUsonombreDestino() == castOther
						.getExtensionCasoUsonombreDestino()) || (this
						.getExtensionCasoUsonombreDestino() != null
						&& castOther.getExtensionCasoUsonombreDestino() != null && this
						.getExtensionCasoUsonombreDestino().equals(
								castOther.getExtensionCasoUsonombreDestino())))
				&& ((this.getExtensionCasoUsoModuloclaveDestino() == castOther
						.getExtensionCasoUsoModuloclaveDestino()) || (this
						.getExtensionCasoUsoModuloclaveDestino() != null
						&& castOther.getExtensionCasoUsoModuloclaveDestino() != null && this
						.getExtensionCasoUsoModuloclaveDestino()
						.equals(castOther
								.getExtensionCasoUsoModuloclaveDestino())))
				&& (this.getPasonumero() == castOther.getPasonumero())
				&& ((this.getPasoTrayectoriaidentificador() == castOther
						.getPasoTrayectoriaidentificador()) || (this
						.getPasoTrayectoriaidentificador() != null
						&& castOther.getPasoTrayectoriaidentificador() != null && this
						.getPasoTrayectoriaidentificador().equals(
								castOther.getPasoTrayectoriaidentificador())))
				&& ((this.getPasoTrayectoriaCasoUsoElementoclave() == castOther
						.getPasoTrayectoriaCasoUsoElementoclave()) || (this
						.getPasoTrayectoriaCasoUsoElementoclave() != null
						&& castOther.getPasoTrayectoriaCasoUsoElementoclave() != null && this
						.getPasoTrayectoriaCasoUsoElementoclave()
						.equals(castOther
								.getPasoTrayectoriaCasoUsoElementoclave())))
				&& (this.getPasoTrayectoriaCasoUsoElementonumero() == castOther
						.getPasoTrayectoriaCasoUsoElementonumero())
				&& ((this.getPasoTrayectoriaCasoUsoElementonombre() == castOther
						.getPasoTrayectoriaCasoUsoElementonombre()) || (this
						.getPasoTrayectoriaCasoUsoElementonombre() != null
						&& castOther.getPasoTrayectoriaCasoUsoElementonombre() != null && this
						.getPasoTrayectoriaCasoUsoElementonombre()
						.equals(castOther
								.getPasoTrayectoriaCasoUsoElementonombre())))
				&& ((this.getPasoTrayectoriaCasoUsoModuloclave() == castOther
						.getPasoTrayectoriaCasoUsoModuloclave()) || (this
						.getPasoTrayectoriaCasoUsoModuloclave() != null
						&& castOther.getPasoTrayectoriaCasoUsoModuloclave() != null && this
						.getPasoTrayectoriaCasoUsoModuloclave()
						.equals(castOther
								.getPasoTrayectoriaCasoUsoModuloclave())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getExtensionCasoUsoclaveOrigen() == null ? 0 : this
						.getExtensionCasoUsoclaveOrigen().hashCode());
		result = 37 * result + this.getExtensionCasoUsonumeroOrigen();
		result = 37
				* result
				+ (getExtensionCasoUsonombreOrigen() == null ? 0 : this
						.getExtensionCasoUsonombreOrigen().hashCode());
		result = 37
				* result
				+ (getExtensionCasoUsoModuloclaveOrigen() == null ? 0 : this
						.getExtensionCasoUsoModuloclaveOrigen().hashCode());
		result = 37
				* result
				+ (getExtensionCasoUsoclaveDestino() == null ? 0 : this
						.getExtensionCasoUsoclaveDestino().hashCode());
		result = 37 * result + this.getExtensionCasoUsonumeroDestino();
		result = 37
				* result
				+ (getExtensionCasoUsonombreDestino() == null ? 0 : this
						.getExtensionCasoUsonombreDestino().hashCode());
		result = 37
				* result
				+ (getExtensionCasoUsoModuloclaveDestino() == null ? 0 : this
						.getExtensionCasoUsoModuloclaveDestino().hashCode());
		result = 37 * result + this.getPasonumero();
		result = 37
				* result
				+ (getPasoTrayectoriaidentificador() == null ? 0 : this
						.getPasoTrayectoriaidentificador().hashCode());
		result = 37
				* result
				+ (getPasoTrayectoriaCasoUsoElementoclave() == null ? 0 : this
						.getPasoTrayectoriaCasoUsoElementoclave().hashCode());
		result = 37 * result + this.getPasoTrayectoriaCasoUsoElementonumero();
		result = 37
				* result
				+ (getPasoTrayectoriaCasoUsoElementonombre() == null ? 0 : this
						.getPasoTrayectoriaCasoUsoElementonombre().hashCode());
		result = 37
				* result
				+ (getPasoTrayectoriaCasoUsoModuloclave() == null ? 0 : this
						.getPasoTrayectoriaCasoUsoModuloclave().hashCode());
		return result;
	}

}
