package mx.prisma.editor.model;

// Generated 05-jun-2015 12:23:22 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;

/**
 * ValorPrePostcondicionId generated by hbm2java
 */
@Embeddable
public class ValorPrePostcondicionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numeroParametro;
	private PostPrecondicion postPrecondicion;
	private Elemento elemento;
	
	public ValorPrePostcondicionId() {
	}

	public ValorPrePostcondicionId(int numeroParametro, PostPrecondicion postPrecondicion, Elemento elemento) {
		this.numeroParametro = numeroParametro;
		this.postPrecondicion = postPrecondicion;
		this.elemento = elemento;
	}

	@Column(name = "numeroParametro", nullable = false)
	public int getNumeroParametro() {
		return this.numeroParametro;
	}

	public void setNumeroParametro(int numeroParametro) {
		this.numeroParametro = numeroParametro;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PostPrecondicionnumero", referencedColumnName = "numero", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PostPretcondicionCasoUsoElementoclave", referencedColumnName = "CasoUsoElementoclave", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PostPrecondicionCasoUsoElementonumero", referencedColumnName = "CasoUsoElementonumero", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PostPrecondicionCasoUsoElementonombre", referencedColumnName = "CasoUsoElementonombre", nullable = false, insertable = false, updatable = false)})
	public PostPrecondicion getPostPrecondicion() {
		return this.postPrecondicion;
	}

	public void setPostPrecondicion(PostPrecondicion postPrecondicion) {
		this.postPrecondicion = postPrecondicion;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "Elementoclave", referencedColumnName = "clave", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "Elementonumero", referencedColumnName = "numero", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "Elementonombre", referencedColumnName = "nombre", nullable = false, insertable = false, updatable = false) })
	public Elemento getElemento() {
		return elemento;
	}

	public void setElemento(Elemento elemento) {
		this.elemento = elemento;
	}
	
	
}
