package mx.prisma.editor.model;

// Generated 05-jun-2015 12:23:22 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ValorParametroMensajeId generated by hbm2java
 */
@Embeddable
public class ValorParametroMensajeId implements java.io.Serializable {

	private int numeroParametro;
	private String mensajeElementoclave;
	private int mensajeElementonumero;
	private String mensajeElementonombre;
	private int tipoParametroidentificador;

	public ValorParametroMensajeId() {
	}

	public ValorParametroMensajeId(int numeroParametro,
			String mensajeElementoclave, int mensajeElementonumero,
			String mensajeElementonombre, int tipoParametroidentificador) {
		this.numeroParametro = numeroParametro;
		this.mensajeElementoclave = mensajeElementoclave;
		this.mensajeElementonumero = mensajeElementonumero;
		this.mensajeElementonombre = mensajeElementonombre;
		this.tipoParametroidentificador = tipoParametroidentificador;
	}

	@Column(name = "numeroParametro", nullable = false)
	public int getNumeroParametro() {
		return this.numeroParametro;
	}

	public void setNumeroParametro(int numeroParametro) {
		this.numeroParametro = numeroParametro;
	}

	@Column(name = "MensajeElementoclave", nullable = false, length = 10)
	public String getMensajeElementoclave() {
		return this.mensajeElementoclave;
	}

	public void setMensajeElementoclave(String mensajeElementoclave) {
		this.mensajeElementoclave = mensajeElementoclave;
	}

	@Column(name = "MensajeElementonumero", nullable = false)
	public int getMensajeElementonumero() {
		return this.mensajeElementonumero;
	}

	public void setMensajeElementonumero(int mensajeElementonumero) {
		this.mensajeElementonumero = mensajeElementonumero;
	}

	@Column(name = "MensajeElementonombre", nullable = false, length = 45)
	public String getMensajeElementonombre() {
		return this.mensajeElementonombre;
	}

	public void setMensajeElementonombre(String mensajeElementonombre) {
		this.mensajeElementonombre = mensajeElementonombre;
	}

	@Column(name = "TipoParametroidentificador", nullable = false)
	public int getTipoParametroidentificador() {
		return this.tipoParametroidentificador;
	}

	public void setTipoParametroidentificador(int tipoParametroidentificador) {
		this.tipoParametroidentificador = tipoParametroidentificador;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ValorParametroMensajeId))
			return false;
		ValorParametroMensajeId castOther = (ValorParametroMensajeId) other;

		return (this.getNumeroParametro() == castOther.getNumeroParametro())
				&& ((this.getMensajeElementoclave() == castOther
						.getMensajeElementoclave()) || (this
						.getMensajeElementoclave() != null
						&& castOther.getMensajeElementoclave() != null && this
						.getMensajeElementoclave().equals(
								castOther.getMensajeElementoclave())))
				&& (this.getMensajeElementonumero() == castOther
						.getMensajeElementonumero())
				&& ((this.getMensajeElementonombre() == castOther
						.getMensajeElementonombre()) || (this
						.getMensajeElementonombre() != null
						&& castOther.getMensajeElementonombre() != null && this
						.getMensajeElementonombre().equals(
								castOther.getMensajeElementonombre())))
				&& (this.getTipoParametroidentificador() == castOther
						.getTipoParametroidentificador());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumeroParametro();
		result = 37
				* result
				+ (getMensajeElementoclave() == null ? 0 : this
						.getMensajeElementoclave().hashCode());
		result = 37 * result + this.getMensajeElementonumero();
		result = 37
				* result
				+ (getMensajeElementonombre() == null ? 0 : this
						.getMensajeElementonombre().hashCode());
		result = 37 * result + this.getTipoParametroidentificador();
		return result;
	}

}
