package mx.prisma.editor.model;

// Generated 05-jun-2015 12:23:22 by Hibernate Tools 4.0.0

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ValorPrePostcondicion generated by hbm2java
 */
@Entity
@Table(name = "ValorPrePostcondicion", catalog = "PRISMA")
public class ValorPrePostcondicion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ValorPrePostcondicionId id;
	
	public ValorPrePostcondicion() {
	}

	public ValorPrePostcondicion(ValorPrePostcondicionId id) {
		this.id = id;
	}

	@EmbeddedId
	public ValorPrePostcondicionId getId() {
		return this.id;
	}

	public void setId(ValorPrePostcondicionId id) {
		this.id = id;
	}



}
