package mx.prisma.editor.model;

// Generated 05-jun-2015 12:23:22 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ValorParametroPasoId generated by hbm2java
 */
@Embeddable
public class ValorParametroPasoId implements java.io.Serializable {

	private int numeroParametro;
	private int pasonumero;
	private String pasoTrayectoriaidentificador;
	private String pasoTrayectoriaCasoUsoElementoclave;
	private int pasoTrayectoriaCasoUsoElementonumero;
	private String pasoTrayectoriaCasoUsoElementonombre;
	private String pasoTrayectoriaCasoUsoModuloclave;
	private int tipoParametroidentificador;

	public ValorParametroPasoId() {
	}

	public ValorParametroPasoId(int numeroParametro, int pasonumero,
			String pasoTrayectoriaidentificador,
			String pasoTrayectoriaCasoUsoElementoclave,
			int pasoTrayectoriaCasoUsoElementonumero,
			String pasoTrayectoriaCasoUsoElementonombre,
			String pasoTrayectoriaCasoUsoModuloclave,
			int tipoParametroidentificador) {
		this.numeroParametro = numeroParametro;
		this.pasonumero = pasonumero;
		this.pasoTrayectoriaidentificador = pasoTrayectoriaidentificador;
		this.pasoTrayectoriaCasoUsoElementoclave = pasoTrayectoriaCasoUsoElementoclave;
		this.pasoTrayectoriaCasoUsoElementonumero = pasoTrayectoriaCasoUsoElementonumero;
		this.pasoTrayectoriaCasoUsoElementonombre = pasoTrayectoriaCasoUsoElementonombre;
		this.pasoTrayectoriaCasoUsoModuloclave = pasoTrayectoriaCasoUsoModuloclave;
		this.tipoParametroidentificador = tipoParametroidentificador;
	}

	@Column(name = "numeroParametro", nullable = false)
	public int getNumeroParametro() {
		return this.numeroParametro;
	}

	public void setNumeroParametro(int numeroParametro) {
		this.numeroParametro = numeroParametro;
	}

	@Column(name = "Pasonumero", nullable = false)
	public int getPasonumero() {
		return this.pasonumero;
	}

	public void setPasonumero(int pasonumero) {
		this.pasonumero = pasonumero;
	}

	@Column(name = "PasoTrayectoriaidentificador", nullable = false, length = 5)
	public String getPasoTrayectoriaidentificador() {
		return this.pasoTrayectoriaidentificador;
	}

	public void setPasoTrayectoriaidentificador(
			String pasoTrayectoriaidentificador) {
		this.pasoTrayectoriaidentificador = pasoTrayectoriaidentificador;
	}

	@Column(name = "PasoTrayectoriaCasoUsoElementoclave", nullable = false, length = 10)
	public String getPasoTrayectoriaCasoUsoElementoclave() {
		return this.pasoTrayectoriaCasoUsoElementoclave;
	}

	public void setPasoTrayectoriaCasoUsoElementoclave(
			String pasoTrayectoriaCasoUsoElementoclave) {
		this.pasoTrayectoriaCasoUsoElementoclave = pasoTrayectoriaCasoUsoElementoclave;
	}

	@Column(name = "PasoTrayectoriaCasoUsoElementonumero", nullable = false)
	public int getPasoTrayectoriaCasoUsoElementonumero() {
		return this.pasoTrayectoriaCasoUsoElementonumero;
	}

	public void setPasoTrayectoriaCasoUsoElementonumero(
			int pasoTrayectoriaCasoUsoElementonumero) {
		this.pasoTrayectoriaCasoUsoElementonumero = pasoTrayectoriaCasoUsoElementonumero;
	}

	@Column(name = "PasoTrayectoriaCasoUsoElementonombre", nullable = false, length = 45)
	public String getPasoTrayectoriaCasoUsoElementonombre() {
		return this.pasoTrayectoriaCasoUsoElementonombre;
	}

	public void setPasoTrayectoriaCasoUsoElementonombre(
			String pasoTrayectoriaCasoUsoElementonombre) {
		this.pasoTrayectoriaCasoUsoElementonombre = pasoTrayectoriaCasoUsoElementonombre;
	}

	@Column(name = "PasoTrayectoriaCasoUsoModuloclave", nullable = false, length = 10)
	public String getPasoTrayectoriaCasoUsoModuloclave() {
		return this.pasoTrayectoriaCasoUsoModuloclave;
	}

	public void setPasoTrayectoriaCasoUsoModuloclave(
			String pasoTrayectoriaCasoUsoModuloclave) {
		this.pasoTrayectoriaCasoUsoModuloclave = pasoTrayectoriaCasoUsoModuloclave;
	}

	@Column(name = "TipoParametroidentificador", nullable = false)
	public int getTipoParametroidentificador() {
		return this.tipoParametroidentificador;
	}

	public void setTipoParametroidentificador(int tipoParametroidentificador) {
		this.tipoParametroidentificador = tipoParametroidentificador;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ValorParametroPasoId))
			return false;
		ValorParametroPasoId castOther = (ValorParametroPasoId) other;

		return (this.getNumeroParametro() == castOther.getNumeroParametro())
				&& (this.getPasonumero() == castOther.getPasonumero())
				&& ((this.getPasoTrayectoriaidentificador() == castOther
						.getPasoTrayectoriaidentificador()) || (this
						.getPasoTrayectoriaidentificador() != null
						&& castOther.getPasoTrayectoriaidentificador() != null && this
						.getPasoTrayectoriaidentificador().equals(
								castOther.getPasoTrayectoriaidentificador())))
				&& ((this.getPasoTrayectoriaCasoUsoElementoclave() == castOther
						.getPasoTrayectoriaCasoUsoElementoclave()) || (this
						.getPasoTrayectoriaCasoUsoElementoclave() != null
						&& castOther.getPasoTrayectoriaCasoUsoElementoclave() != null && this
						.getPasoTrayectoriaCasoUsoElementoclave()
						.equals(castOther
								.getPasoTrayectoriaCasoUsoElementoclave())))
				&& (this.getPasoTrayectoriaCasoUsoElementonumero() == castOther
						.getPasoTrayectoriaCasoUsoElementonumero())
				&& ((this.getPasoTrayectoriaCasoUsoElementonombre() == castOther
						.getPasoTrayectoriaCasoUsoElementonombre()) || (this
						.getPasoTrayectoriaCasoUsoElementonombre() != null
						&& castOther.getPasoTrayectoriaCasoUsoElementonombre() != null && this
						.getPasoTrayectoriaCasoUsoElementonombre()
						.equals(castOther
								.getPasoTrayectoriaCasoUsoElementonombre())))
				&& ((this.getPasoTrayectoriaCasoUsoModuloclave() == castOther
						.getPasoTrayectoriaCasoUsoModuloclave()) || (this
						.getPasoTrayectoriaCasoUsoModuloclave() != null
						&& castOther.getPasoTrayectoriaCasoUsoModuloclave() != null && this
						.getPasoTrayectoriaCasoUsoModuloclave()
						.equals(castOther
								.getPasoTrayectoriaCasoUsoModuloclave())))
				&& (this.getTipoParametroidentificador() == castOther
						.getTipoParametroidentificador());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumeroParametro();
		result = 37 * result + this.getPasonumero();
		result = 37
				* result
				+ (getPasoTrayectoriaidentificador() == null ? 0 : this
						.getPasoTrayectoriaidentificador().hashCode());
		result = 37
				* result
				+ (getPasoTrayectoriaCasoUsoElementoclave() == null ? 0 : this
						.getPasoTrayectoriaCasoUsoElementoclave().hashCode());
		result = 37 * result + this.getPasoTrayectoriaCasoUsoElementonumero();
		result = 37
				* result
				+ (getPasoTrayectoriaCasoUsoElementonombre() == null ? 0 : this
						.getPasoTrayectoriaCasoUsoElementonombre().hashCode());
		result = 37
				* result
				+ (getPasoTrayectoriaCasoUsoModuloclave() == null ? 0 : this
						.getPasoTrayectoriaCasoUsoModuloclave().hashCode());
		result = 37 * result + this.getTipoParametroidentificador();
		return result;
	}

}
