package mx.prisma.editor.model;

// Generated 05-jun-2015 12:23:22 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ValorParametroExtension generated by hbm2java
 */
@Entity
@Table(name = "ValorParametroExtension", catalog = "PRISMA")
public class ValorParametroExtension implements java.io.Serializable {

	private ValorParametroExtensionId id;

	public ValorParametroExtension() {
	}

	public ValorParametroExtension(ValorParametroExtensionId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "extensionCasoUsoclaveOrigen", column = @Column(name = "ExtensionCasoUsoclave_origen", nullable = false, length = 10)),
			@AttributeOverride(name = "extensionCasoUsonumeroOrigen", column = @Column(name = "ExtensionCasoUsonumero_origen", nullable = false)),
			@AttributeOverride(name = "extensionCasoUsonombreOrigen", column = @Column(name = "ExtensionCasoUsonombre_origen", nullable = false, length = 45)),
			@AttributeOverride(name = "extensionCasoUsoModuloclaveOrigen", column = @Column(name = "ExtensionCasoUsoModuloclave_origen", nullable = false, length = 10)),
			@AttributeOverride(name = "extensionCasoUsoclaveDestino", column = @Column(name = "ExtensionCasoUsoclave_destino", nullable = false, length = 10)),
			@AttributeOverride(name = "extensionCasoUsonumeroDestino", column = @Column(name = "ExtensionCasoUsonumero_destino", nullable = false)),
			@AttributeOverride(name = "extensionCasoUsonombreDestino", column = @Column(name = "ExtensionCasoUsonombre_destino", nullable = false, length = 45)),
			@AttributeOverride(name = "extensionCasoUsoModuloclaveDestino", column = @Column(name = "ExtensionCasoUsoModuloclave_destino", nullable = false, length = 10)),
			@AttributeOverride(name = "pasonumero", column = @Column(name = "Pasonumero", nullable = false)),
			@AttributeOverride(name = "pasoTrayectoriaidentificador", column = @Column(name = "PasoTrayectoriaidentificador", nullable = false, length = 5)),
			@AttributeOverride(name = "pasoTrayectoriaCasoUsoElementoclave", column = @Column(name = "PasoTrayectoriaCasoUsoElementoclave", nullable = false, length = 10)),
			@AttributeOverride(name = "pasoTrayectoriaCasoUsoElementonumero", column = @Column(name = "PasoTrayectoriaCasoUsoElementonumero", nullable = false)),
			@AttributeOverride(name = "pasoTrayectoriaCasoUsoElementonombre", column = @Column(name = "PasoTrayectoriaCasoUsoElementonombre", nullable = false, length = 45)),
			@AttributeOverride(name = "pasoTrayectoriaCasoUsoModuloclave", column = @Column(name = "PasoTrayectoriaCasoUsoModuloclave", nullable = false, length = 10)) })
	public ValorParametroExtensionId getId() {
		return this.id;
	}

	public void setId(ValorParametroExtensionId id) {
		this.id = id;
	}

}
